### ISSUE TITLE
addon.tab.getScratchVM() sometimes doesn't work

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#109]
To fix this, we should be injecting the code directly from the content script, instead of injecting a script tag that needs to load, and then execute.
I'm not 100% sure why this happens, but griffpatch said this works better.

**Comment by BoomerScratch** [comment]
My userscript injects a `<script>` element in the head so it sets up the trap before the other scripts load. In https://github.com/ScratchAddons/ScratchAddons/blob/5f4c20f76d0e29fdc8bfa628231aec8945bae1aa/content-scripts/find-vm-injector.js#L1, use `document.head` instead of `document.documentElement`. Maybe then it works better. If that still doesn't work, set the innerHTML to the contents of https://github.com/ScratchAddons/ScratchAddons/blob/master/content-scripts/inject/find-vm.js instead of setting the src.

**Comment by WorldLanguages** [comment]
When that executes there's no head yet.
We already agreed with griffpatch on the best method: inject directly to the page, and use an IIFE to preserve linting/syntax highlighting in the code.
Will update it in an upcoming PR.

**Comment by BoomerScratch** [comment]
> When that executes there's no head yet.

Huh? My usercript works just fine, and it runs at `document_start`.

**Comment by WorldLanguages** [comment]
Hmm looks like you're right. I'm not sure why I remembered having no head yet.
Oh, I know why: the body is not yet available, but the head is.

**Comment by BoomerScratch** [comment]
@WorldLanguages Yes, you are right. Can you try to see if it works?
