### ISSUE TITLE
[Feature] better console.logging(?)

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#136]
**Is your feature request related to a problem? Please describe.**

when i am developing top tier epic super cool very cool addons and i use the best debugging method (`console.log('yo')`) sometimes i get confused because the console.logs are pretty simple (`[addon name] the actual console.log`) and its hard to tell whats going on there
**Describe the solution you'd like**

so maybe the [addon name] part could use some cool css console logging in colour stuff to make it clearer which addon is saying what (and also that its from scratchaddons)

please see my mockup attached below (its kinda like minecraft but in the javascript console)
![image](https://user-images.githubusercontent.com/40470736/91748293-1104d900-ebc0-11ea-905b-e44b46a5648b.png)
the advantage is that the addon name is in bold and coloured which makes it stand out more and be cooler

**Describe alternatives you've considered**

i could just not call the console thing console and use the default console.log while debugging but i am stupid and likely will forget about it

**Additional context**

im stupid

**Comment by WorldLanguages** [comment]
yo nice idea!

**Comment by WorldLanguages** [comment]
Hmm, I'm not 100% sure if this is possible:
https://github.com/ScratchAddons/ScratchAddons/blob/master/content-scripts/inject/run-userscript.js#L15
Keep in mind that without this "bind" magic, all console logs would come from the same file - right now, console logs correctly say what line they're from.
In order to add CSS I think, the last argument needs to be a special string. However, I don't think bind allows us to put arguments at front, not at last. We're getting into hacky JS territory.

**Comment by WorldLanguages** [comment]
Nevermind, the CSS doesn't necessarily have to be the last argument - at least in Chrome. For example, this works: `console.log("%c[addon name]", "color: blue", "beep", "boop");`
