### ISSUE TITLE
Add TurboWarp Blocks to the Editor

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1429]
**TurboWarp is Amazing**

I was wondering if we could apply TurboWarp's extended features into the Scratch Editor. The blocks are very useful, but I am not able to autosave to my scratch account, so I was wondering if we could create a method to save TurboWarp Projects to Scratch Accounts or use those blocks in the Scratch Editor!

**Comment by apple502j** [comment]
You should guess why the block is called "TurboWarp Blocks" before suggesting.

**Comment by Hans5958** [comment]
@apple502j 

Oh, come on. At least don't give such vague response by telling people to get lost and tell me what's the reason of this is impossible. Is it because those blocks are from TurboWarp natively, or is it because it is actually a hidden block that functionality exists on Scratch but it is not possible to add it due to some limitation, or is it because of some other third thing that is not that known.

Some things that are too obvious for someone might not obvious to other people. This should be kept in mine, especially when facing youngsters who are still naive. Heck, even I don't understand, and so I am left with assumptions and not a clear answer. So, please.

**Comment by GarboMuffin** [comment]
apple is right. The new blocks in TW are hopelessly broken in Scratch because they are new blocks with new opcodes that Scratch can't interpret, not weird hidden blocks. Even if you get them to load for yourself, good luck having it load for everyone that views your project

**Comment by Hans5958** [comment]
I'm not saying that Apple is not wrong. What I'm saying is that people should be left with a clear response why this suggestion won't work, not being left with a vague response.

Also, I thank you for the explanation. I appreciate it.
