### ISSUE TITLE
High Quality Pen

### ISSUE THREAD

**Issue by aetinx** [ScratchAddons/ScratchAddons#1439]
Um, add HQ Pen from Turbowarp?

**Comment by WorldLanguages** [comment]
Hmm, I honestly doubt it's possible as an addon

**Comment by MiniCoder11** [comment]
HQ Pen from TurboWarp was achieved by rewriting the canvas rendering system. As far as I know, injectables don't have _that_ much access to the VM to perform such a large change after the page loads (and even if they could, it would likely take a large amount of research, trial, and error to achieve). However, I'd like someone to prove this is possible because it is a very nice feature. Previous attempts at achieving the effect haven't worked (such as increasing canvas resolution/DPI) because at increased resolutions, Scratch continues to render at an unscaled size (A 720p canvas would have a tiny 360p image rendered onto it and the rest would be left as blank space).

**Comment by WorldLanguages** [comment]
Tagging @GarboMuffin in case he wants to take it, not sure who else could otherwise.
Apparently TurboWarp's approach to high quality pen is not that complex to do as an addon, according to some old messages I found on our discord server.

**Comment by GarboMuffin** [comment]
This is definitely possible as an addon, but TW's hq pen has some noteworthy flaws:

 - Performance - Sometimes you're rendering 20x more pixels with hq pen enabled. That is *slow*. TW can only accept that because the compiler is usually an order of magnitude faster than Scratch.
 - Not all projects will look right, try https://turbowarp.org/322341152/fullscreen?hqpen at various resolutions (https://user-images.githubusercontent.com/33787854/106162851-2b7eb680-614e-11eb-93a2-f126eae1232d.png) For the most part, I believe these are unfixable side effects of making pen high quality.
 - It probably affects the behavior of <touching color?>

**Comment by MiniCoder11** [comment]
> * Not all projects will look right, try https://turbowarp.org/322341152/fullscreen?hqpen at various resolutions (https://user-images.githubusercontent.com/33787854/106162851-2b7eb680-614e-11eb-93a2-f126eae1232d.png) For the most part, I believe these are unfixable side effects of making pen high quality.

Is that specifically a TurboWarp bug, or does it only occur because the project was built with costumes specifically sized to account for the fact that Scratch's low resolution would fill in the gaps? It seems the gaps only happen for sprite sizes that aren't direct multiples of ten.

**Comment by RedGuy12** [comment]
This should probably be something like Fn+Green flag (trying to find a key not used yet :P ) only
________________________________

**Comment by mxmou** [comment]
> This should probably be something like Fn+Green flag (trying to find a key not used yet :P ) only

Or an option in the Edit menu.

**Comment by areeq0325** [comment]
<kbd>Alt</kbd>+<kbd>Shift</kbd>+click?

**Comment by TheColaber** [comment]
Why not just Tab+Click. But anyway the keybinding is not the issue.

**Comment by sargent-coding** [comment]
Why not do Alt + greenFlag to get a dropdown of the options?

**Comment by CuriousG2** [comment]
> 
> 
> Why not do Alt + greenFlag to get a dropdown of the options?

That's what I was thinking. It wouldn't be as quick for the user though.

**Comment by WorldLanguages** [comment]
No need to discuss keybinds until this addon exists, folks

**Comment by GarboMuffin** [comment]
> 
> 
> > * Not all projects will look right, try https://turbowarp.org/322341152/fullscreen?hqpen at various resolutions (https://user-images.githubusercontent.com/33787854/106162851-2b7eb680-614e-11eb-93a2-f126eae1232d.png) For the most part, I believe these are unfixable side effects of making pen high quality.
> 
> Is that specifically a TurboWarp bug, or does it only occur because the project was built with costumes specifically sized to account for the fact that Scratch's low resolution would fill in the gaps? It seems the gaps only happen for sprite sizes that aren't direct multiples of ten.

It's a fundamental problem with how high quality pen works in its current state, not an issue with the project or an issue in the TW compiler. The end result is that some projects will look wrong in weird inconsistent ways that will confuse users and project creators that inevitably get comments about weird lines.

Maybe it's fixable, but I'm not optimistic though I haven't spent much time looking into it.

**Comment by Mr-Anonymous75** [comment]
> > > * Not all projects will look right, try https://turbowarp.org/322341152/fullscreen?hqpen at various resolutions (https://user-images.githubusercontent.com/33787854/106162851-2b7eb680-614e-11eb-93a2-f126eae1232d.png) For the most part, I believe these are unfixable side effects of making pen high quality.
> > 
> > 
> > Is that specifically a TurboWarp bug, or does it only occur because the project was built with costumes specifically sized to account for the fact that Scratch's low resolution would fill in the gaps? It seems the gaps only happen for sprite sizes that aren't direct multiples of ten.
> 
> It's a fundamental problem with how high quality pen works in its current state, not an issue with the project or an issue in the TW compiler. The end result is that some projects will look wrong in weird inconsistent ways that will confuse users and project creators that inevitably get comments about weird lines.
> 
> Maybe it's fixable, but I'm not optimistic (though I haven't spent much time looking into it.)

I just tried the project again - and honestly, I can't see anything wrong with it with HQ Pen 🤔

**Comment by GarboMuffin** [comment]
I think I fixed most of its compatibility issues, so, maybe it will be here eventually. Still terrible for performance though.

**Comment by lisa-wolfgang** [comment]
This should probably be implemented as an option in the TurboWarp embed addon.

**Comment by aetinx** [comment]
Oh my, this is still going on after about a whole year (-3 days)!

**Comment by Samq64** [comment]
There's an unused from TurboWarp label that would fit well with this issue.

**Comment by DNin01** [comment]
To clarify the closure, this was resolved by #5214, or at least it addresses this issue enough for it to no longer be worth working on.

**Comment by aetinx** [comment]
No way my issue was closed after over 4 years... LMAOOOOOOO

**Comment by WorldLanguages** [comment]
Actually, over 2 years :P

**Comment by aetinx** [comment]
> Actually, over 2 years :P

Fuck, I miscalculated.
