### ISSUE TITLE
Ability to set the language manually

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1460]
**Is your feature request related to a problem? Please describe.**

I don't like the fact that the language is set automaticaly to the browser language. (One of my browsers is in english, and I can't set the browser language to Romanian for some reason.)

**Describe the solution you'd like**

I'd like a dropdown in the settings page that can be used to manually set the ScratchAddons language. The default language will still be the browser language, but the users will also be able to manually set it.

**Describe alternatives you've considered**

An option in "more settings".

**Additional context**

Something like this:

<img width="131" alt="sa3" src="https://user-images.githubusercontent.com/69812464/106294917-74bb2d00-6258-11eb-9df5-8f7c16ff7180.png">

**Comment by mxmou** [comment]
> I don't like the fact that the language is set automaticaly to the browser language.

All browser extensions work this way.

**Comment by WorldLanguages** [comment]
Unfortunately this is how browsers work. It's up to them to support a way to change what language is used when calling `chrome.i18n.getMessage()` in a certain extension.
Also, keep in mind that except for the settings page, the popup and persistent scripts, we use the same language as Scratch in order to be consistent. We *could* move everything into this system, but it wouldn't be possible to change the language of the extension name or description (it would still be stuck with your browser's UI language)

**Comment by superscratch444tre** [comment]
>We *could* move everything into this system, but it wouldn't be possible to change the language of the extension name or description (it would still be stuck with your browser's UI language)

It would also be ok, the most important things are the popup and the settings page.

**Comment by Secret-chest** [comment]
I don't know. Something like this maybe:
    if forceLanguage == True:
        language = languageSetting
    else:
        language = browser language idk

**Comment by apple502j** [comment]
wontfix for now. If you cannot change your browser's language, it's the browser's problem.
