### ISSUE TITLE
Manifest v3: move from background page to service worker

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1538]
1. ~~The service worker needs to be in the root folder, and has to be a single JS file - so we'll have two files in root now, manifest.json and sw.js~~ They can be in subfolders starting in Chrome 93.
2. ~~Service workers don't support modules yet, so it's not worth migrating until then.~~ They now do in Chrome 92. The sw.js file in root would just be a bunch of imports from files on background/*
3. I'm not entirely sure how objects like `window.scratchAddons` work in the service worker model. Hopefully these aren't cleared after the service worker is put to sleep? (EDIT: data isn't cleared, unlike a typical service worker) (edit 2: i was wrong, it is cleared after 5 minutes max)

**Comment by DNin01** [comment]
What will we do about number 3?

Luckily, moving all the background scripts into a single file that will eventually become the service worker shouldn't be too hard. The only thing present in the background page are scripts, so we would just create a new script that imports those, and to maintain MV2 compatibility and support older Firefox versions, load that mega-script into the background page (we could make a PR for that right now!). The most difficult part will be working out all the other differences between background pages and service workers.

**Comment by WorldLanguages** [comment]
> What will we do about number 3?

Well, Chrome kills service workers less frequently now. Also after some testing, the behavior doesn't seem that bad. We just have to make sure all event listeners are registered at the top level.

**Comment by DNin01** [comment]
But are there going to be any issues related to variables in the service worker getting erased upon termination? The Chrome Developers documentation does say[^1]:
> Any global variables you set will be lost if the service worker shuts down.

I guess we could set alarms every 30 seconds now - that's possible since Chrome 120[^3]. I don't know for sure, but it seems like, if I understand correctly, that would theoretically keep the service worker alive indefinitely, since that's exactly how long it takes for it to be shut down, but there might still be some edge cases. Plus, we probably want to cover versions of Chrome older than that.

In summary, there might be ways to prevent the service worker from being terminated automatically, but we should expect it to still be terminated at times and keep browser support in mind. It's a good idea to intentionally let it terminate if the user hasn't been using Scratch Addons or on Scratch for a little while (say, 5 minutes). If it was terminated, we can re-declare all the global variables by regenerating or loading them from [a session storage space](https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/#persist-data). It is best practice to design service workers around being disposable[^2]:
> Events and calls to extension APIs reset these timers, and if the service worker has gone dormant, an incoming event will revive them. Nevertheless, you should design your service worker to be resilient against unexpected termination.
>
> To optimize the resource consumption of your extension, avoid keeping your service worker alive indefinitely if possible. Test your extensions to ensure that you're not doing this unintentionally.

[^1]: https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/#persist-data
[^2]: https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/#idle-shutdown
[^3]: https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/#chrome-120

**Comment by WorldLanguages** [comment]
> And some variables from the service worker could maybe be moved to session storage so we don't have to worry about their persistence.

I'm not sure if that will be necessary. I guess it will depend on each background event listener we use.

Just one thing I forgot to test, but I assume works as expected: if there's a scratch.mit.edu tab open, the service worker is terminated, and after some time the sw is woken up (either by some random event or that tab sending it a message) then I believe the tab can still communicate with the service worker, even though it's technically a different SW session from the one that was available when the content script loaded. Hopefully that's the case as it would be very stupid if it didn't work. But I don't think I tested for this case.

**Comment by DNin01** [comment]
> > And some variables from the service worker could maybe be moved to session storage so we don't have to worry about their persistence.
> 
> I'm not sure if that will be necessary. I guess it will depend on each background event listener we use.

Yeah, we'd only need to perform this with variables whose values we want to be persistent (like the Scratch Addons object, for instance?). Temporary variables would be safe to discard after they have been used. Is that what you meant? Won't we have to store any dynamic data that we don't want to go away in storage?

**Comment by DNin01** [comment]
And in that case, it might not be a bad idea to do this with some of our current background page variables before the switch to a service worker, to help with the migration process later.

**Comment by DNin01** [comment]
> Most data in the scratchAddons object isn't intrinsically related to the browser session itself - think addon settings, Scratch auth data, addon manifests. This type of data can be updated/regenerated at any time, so it's not necessary to persist it during the length of the session, it can just be regenerated when needed.

Would that drastically hurt performance or would it be okay? Are there any improvements we can make to speed up that routine?

It doesn't really matter if it takes a few seconds to "wake up" Scratch Addons after several minutes of inactivity, but we probably don't want this to impact the experience of actively using Scratch.

**Comment by DNin01** [comment]
Related: #6355

**Comment by DNin01** [comment]
> > Would that drastically hurt performance or would it be okay?
> 
> The performance of Scratch itself or are you referring to something else?
> 
> All communication between tabs and the background context are async, so it wouldn't really affect anything. The only situation I can imagine being slow, is opening the extension popup after the service worker was terminated.

The performance of all the different parts of Scratch Addons. Like, would addons become any slower? Would the settings page take that much longer to open?

**Comment by WorldLanguages** [comment]
> would addons become any slower (would their scripts and styles take longer to inject)?

Yes. For example, if the user has website dark mode on, and clicks a link while the service worker is terminated, then the screen will flash white for a moment.

> Would the settings page take that much longer to open?

It would take longer, yeah.

**Comment by DNin01** [comment]
> > would addons become any slower (would their scripts and styles take longer to inject)?
> 
> Yes. For example, if the user has website dark mode on, and clicks a link while the service worker is terminated, then the screen will flash white for a moment.

I'm not familiar with everything our current background page needs to do, but I think that might be solvable by storing the state of addons and settings in memory somewhere, instead of in the service worker. That way, we wouldn't have to spend time regenerating any data until the extension is restarted or has settings changed. We're limited to 10 MB (1 MB if we plan to support Chrome versions under 112)[^1], so we should be mindful about what to keep in there.

Would that be possible or is there more to it?

[^1]: https://developer.chrome.com/docs/extensions/reference/api/storage#storage_areas

**Comment by WorldLanguages** [comment]
There are some more comments about this at issue #4561

The general idea is that addons like `scratchr2` and `dark-www` are somewhat special as they need to load into the page as soon as possible (specially to avoid drastic layout changes when clicking links and navigating). Right now (and always since this project has existed) the background context is responsible of telling each tab which scripts and styles it's supposed to inject into the page. Some addons declare `injectAsStyleElt` which is supposed to speed up the injection of its styles, by inlining the CSS in `<style>` elements, instead of using a `<link rel="stylesheet" href="(url)">` indirect approach.
However, the optimizations are entirely best-effort. For example, if you set scratch.mit.edu as the startup page of your browser, and completely restart your browser, dark mode might take one second or two to apply (as it takes some time for the background context to startup and get ready). The service worker potentially terminating makes this more likely to happen, but how often it will actually happen (and whether users will actually be pissed off) will strongly depend on how Chrome decides where and when to terminate service workers.

**Comment by WorldLanguages** [comment]
In Chromium, our background context is now a service worker.
