### ISSUE TITLE
Onion skinning bugs when zooming in

### ISSUE THREAD

**Issue by Riptide-Scratch** [ScratchAddons/ScratchAddons#1661]
**Onion skinning bug**

**To Reproduce**

1. Go to costume editor
2. Spam zoom in
3. See error

Max zoom
![bug report](https://user-images.githubusercontent.com/70417080/109076990-565a1d00-76b0-11eb-8b0b-1ec22f1dfbcc.jpg)
Normal zoom
![control report](https://user-images.githubusercontent.com/70417080/109077072-725dbe80-76b0-11eb-92e3-cf54e64be18f.jpg)

**Comment by retronbv** [comment]
what is the error?

**Comment by WorldLanguages** [comment]
Can you elaborate what the error is? Does it not happen with the onion skinning addon disabled?

**Comment by GarboMuffin** [comment]
Apparently zooming in very far with onion skinning causes issues because of how paper.js draws transparent layers. It seems that in Chrome this eventually results in the onion layers becoming invisible, while in Firefox it throws an error that breaks the editor, and in both browsers it causes performance issues. I assume that's what this issue is talking about.

I believe that this can be fixed or at least worked around
