### ISSUE TITLE
Double clicking text centers everything

### ISSUE THREAD

**Issue by leahcimto** [ScratchAddons/ScratchAddons#1866]
**Describe the bug**
When I double click on text, the whole gets centered
**To Reproduce**

1. Go to any page
2. Double click on text you see
3. Notice that everything is centered

**Expected behavior**
Things shouldn't be centered. 

**Screenshots**

<img width="1431" alt="Screen Shot 2021-03-14 at 9 36 30 AM" src="https://user-images.githubusercontent.com/68165163/111070580-c3d7bd00-84a8-11eb-9a8b-02c7a474c38f.png">

<img width="1426" alt="Screen Shot 2021-03-14 at 9 37 50 AM" src="https://user-images.githubusercontent.com/68165163/111070620-f2ee2e80-84a8-11eb-933c-c8f571d459cd.png">

**Device (please complete the following information):**

- OS: macOS Big Sur 11.2.2
- Browser: Chrome
- Version: 88

**Additional context**
none

**Comment by RedGuy12** [comment]
What addons do you have? Can you disable each one by one?
________________________________
From: leahcimto ***@***.***>
Sent: Sunday, March 14, 2021 8:38:22 AM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Double clicking text centers everything (#1866)


Describe the bug
When I double click on text, the whole gets centered
To Reproduce

  1.  Go to any page
  2.  Double click on text you see
  3.  Notice that everything is centered

Expected behavior
Things shouldn't be centered.

Screenshots

[Screen Shot 2021-03-14 at 9 36 30 AM]<https://user-images.githubusercontent.com/68165163/111070580-c3d7bd00-84a8-11eb-9a8b-02c7a474c38f.png>

[Screen Shot 2021-03-14 at 9 37 50 AM]<https://user-images.githubusercontent.com/68165163/111070620-f2ee2e80-84a8-11eb-933c-c8f571d459cd.png>

Device (please complete the following information):

  *   OS: macOS Big Sur 11.2.2
  *   Browser: Chrome
  *   Version: 88

Additional context
none

**Comment by WorldLanguages** [comment]
Huh, this is weird. We can't do much until you identify the specific addon doing this

**Comment by leahcimto** [comment]
Sorry, just realized it was another userscript I had.

**Comment by WorldLanguages** [comment]
(huh, looks like we don't have an "invalid tag" anymore)
