### ISSUE TITLE
"Most loves" category on profile stats has no comma

### ISSUE THREAD

**Issue by 1132262GitHub** [ScratchAddons/ScratchAddons#1890]
**Describe the bug**

"Most loves" category on profile stats has no comma. All the other categories have commas.

**To Reproduce**

1. Go to a user profile
2. Scroll down to '. Statistics'

**Expected behavior**

"Most loves" would have a comma like the rest of the categories.

**Screenshots**

<img width="952" alt="Screen Shot 2021-03-15 at 4 07 09 PM" src="https://user-images.githubusercontent.com/59401608/111232528-8195a500-85a8-11eb-86c0-d7da932dca65.png">

**Device (please complete the following information):**

- MacOS Big Sure
- Chrome (Brave) 88

>

**Comment by RedGuy12** [comment]
Cc @mxmou
________________________________
From: 1132262GitHub ***@***.***>
Sent: Monday, March 15, 2021 6:08:02 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] "Most loves" category on profile stats has no comma (#1890)


Describe the bug

"Most loves" category on profile stats has no comma. All the other categories have commas.

To Reproduce

  1.  Go to a user profile
  2.  Scroll down to '. Statistics'
  3.  See error

Expected behavior

"Most loves" would have a comma like the rest of the categories.

Screenshots

[Screen Shot 2021-03-15 at 4 07 09 PM]<https://user-images.githubusercontent.com/59401608/111232528-8195a500-85a8-11eb-86c0-d7da932dca65.png>

Device (please complete the following information):

  *   MacOS Big Sure
  *   Chrome (Brave) 88

**Comment by mxmou** [comment]
This only applies to the number in parentheses (most loved by location).

**Comment by scratchusernamemrtbts** [comment]
>     MacOS Big Sure

typo it's MacOS Big Sur
