### ISSUE TITLE
On mac, ctrl clicking the flag brings up context menu instead of muting

### ISSUE THREAD

**Issue by 1132262GitHub** [ScratchAddons/ScratchAddons#1891]
**Describe the bug**

On mac, ctrl clicking the flag brings up context menu instead of muting the project.

**To Reproduce**

1. Go to a project.
2. Right click flag.
3. See error

**Expected behavior**

It would mute the project instead of displaying a context menu.
Something like:

> window.addEventListener('contextmenu', function (e) { 
// mute project
e.preventDefault(); 
}, false);

should fix it.

**Screenshots**

<img width="393" alt="Screen Shot 2021-03-15 at 4 26 45 PM" src="https://user-images.githubusercontent.com/59401608/111234186-3d57d400-85ab-11eb-897e-8e99005cc679.png">
<img width="255" alt="Screen Shot 2021-03-15 at 4 27 16 PM" src="https://user-images.githubusercontent.com/59401608/111234221-51033a80-85ab-11eb-859f-0a927133a0a8.png">

**Device (please complete the following information):**

- MacOS Big Sure
- Chrome (Brave) 88

>

**Comment by RedGuy12** [comment]
So on mac ctrl+click=right click?
________________________________
From: 1132262GitHub ***@***.***>
Sent: Monday, March 15, 2021 6:27:57 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] On mac, ctrl clicking the flag brings up context menu instead of muting (#1891)


Describe the bug

On mac, ctrl clicking the flag brings up context menu instead of muting the project.

To Reproduce

  1.  Go to a project.
  2.  Right click flag.
  3.  See error

Expected behavior

It would mute the project instead of displaying a context menu.
Something like:

window.addEventListener('contextmenu', function (e) {
// mute project
e.preventDefault();
}, false);

should fix it.

Screenshots

[Screen Shot 2021-03-15 at 4 26 45 PM]<https://user-images.githubusercontent.com/59401608/111234186-3d57d400-85ab-11eb-897e-8e99005cc679.png>

[Screen Shot 2021-03-15 at 4 27 16 PM]<https://user-images.githubusercontent.com/59401608/111234221-51033a80-85ab-11eb-859f-0a927133a0a8.png>

Device (please complete the following information):

  *   MacOS Big Sure
  *   Chrome (Brave) 88

**Comment by RedGuy12** [comment]
Cc @thecolaber
________________________________
From: 1132262GitHub ***@***.***>
Sent: Monday, March 15, 2021 6:27:57 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] On mac, ctrl clicking the flag brings up context menu instead of muting (#1891)


Describe the bug

On mac, ctrl clicking the flag brings up context menu instead of muting the project.

To Reproduce

  1.  Go to a project.
  2.  Right click flag.
  3.  See error

Expected behavior

It would mute the project instead of displaying a context menu.
Something like:

window.addEventListener('contextmenu', function (e) {
// mute project
e.preventDefault();
}, false);

should fix it.

Screenshots

[Screen Shot 2021-03-15 at 4 26 45 PM]<https://user-images.githubusercontent.com/59401608/111234186-3d57d400-85ab-11eb-897e-8e99005cc679.png>

[Screen Shot 2021-03-15 at 4 27 16 PM]<https://user-images.githubusercontent.com/59401608/111234221-51033a80-85ab-11eb-859f-0a927133a0a8.png>

Device (please complete the following information):

  *   MacOS Big Sure
  *   Chrome (Brave) 88

**Comment by retronbv** [comment]
> So on mac ctrl+click=right click?

Yes

**Comment by retronbv** [comment]
> * MacOS Big Sure

p.s. it’s Big Sur not Big Sure

**Comment by GrahamSH-LLK** [comment]
I have a feeling it should be Cmd + click on mac?

**Comment by retronbv** [comment]
> I have a feeling it should be Cmd + click on mac?

What do you mean by this? I can confirm (as a Mac user) that CTRL+Click opens the right click context menu

**Comment by GrahamSH-LLK** [comment]
> > I have a feeling it should be Cmd + click on mac?
> 
> What do you mean by this? I can confirm (as a Mac user) that CTRL+Click opens the right click context menu

To mute

**Comment by retronbv** [comment]
> > > I have a feeling it should be Cmd + click on mac?
> > 
> > 
> > What do you mean by this? I can confirm (as a Mac user) that CTRL+Click opens the right click context menu
> 
> To mute

Oh, we will have to see if there is a conflict with cmd+click on Mac

**Comment by 1132262GitHub** [comment]
Currently, cmd click just re-starts the project, but that should be easy to change.
