### ISSUE TITLE
Drop text files onto lists, maybe into "ask and wait" prompt

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#1988]
Not exactly a *new* addon request, but building on the awesome work in #1916: how about an addon or option to allow for dropping text files into lists (and maybe the "ask and wait" prompt)? Lists are already pretty much the standard way to exchange data between the system (or some external resource) and a Scratch project, via the "import" and "export" options, or simply copying to clipboard from a save string shown as an item in the list. So, it'd be pretty cool to be able to drop a saved text file (such as exported from a list or downloaded from another program/site) right into a list watcher! Ditto for the "ask and wait" prompt, for single-line text files anyway.

This is based on my oooold feature request [here](https://github.com/LLK/scratch-gui/issues/268), BTW :P

(See ~~*spooky imminent issue reference*~~ #1990 for an infinitely stranger suggestion based off this.)

**Comment by SheepTester** [comment]
Conveniently, each visible list watcher has its own right click menu under `<body>`, waiting to be opened by the user. There's no direct way to determine which list corresponds to which right click menu, I think, but we could simulate a contextmenu event (`.dispatchEvent(new Event('contextmenu', { bubbles: true }))`) and then click the "Import" button of whatever menu that opens.

Scratch uses [a library for parsing CSV files](https://github.com/LLK/scratch-gui/blob/develop/src/lib/import-csv.js). We could avoid importing this by overriding a few DOM methods:

```js
const appendChild = document.body.appendChild;
document.body.appendChild = (fileInput) => {
  // Prevent Scratch from opening the file input dialog
  fileInput.click = () => {};
  // Insert files from the drop event into the file input
  fileInput.files = dropEvent.data.whatever;
  // Restore appendChild to <body>
  document.body.appendChild = appendChild;
};
importBtn.click();
```
This is rather janky, though

**Comment by SheepTester** [comment]
Ask and wait, in contrast, is a lot simpler since you can just set `input.value` and then click the convenient check mark button
<img width="51" src="https://user-images.githubusercontent.com/22133785/112780343-7fe2cd00-8ffd-11eb-8108-de639ce69f36.png">


Should it automatically submit the text from the file, or should it just paste the text into the text box and have the user manually submit?

**Comment by towerofnix** [comment]
> Should it automatically submit the text from the file, or should it just paste the text into the text box and have the user manually submit?

@SheepTester I think it should let the user manually submit. It lets them make sure they've dropped the right file, and it's all imported properly. It also lets them make any wanted modifications before entering.

One question I'd like to raise is, what should happen when dropping a text file with multiple lines into the "ask and wait" prompt? Probably, line breaks should just be replaced with spaces?

**Comment by SheepTester** [comment]
> One question I'd like to raise is, what should happen when dropping a text file with multiple lines into the "ask and wait" prompt? Probably, line breaks should just be replaced with spaces?

For a naïve implementation that sets `input.value` to the text file contents, I believe the browser removes the newline characters because the text box is an `<input>` element

Alternatively, it could insert one line at a time, then automatically submitting when it encounters a newline character, kind of like the command prompt when I paste in multiple commands separated by newlines). This would help with importing from a text file exported from a list, though I suppose they could just drag and drop into the list since that'll also be added.

If we want the user to make modifications before submitting, a very sophisticated solution could be to withhold the rest of the lines and only insert the first line; then if the user submits, the project can ask again for the next line, which would be automatically inserted. This would probably be very confusing for the user without some fancy UI though

Removing or replacing the newline characters is probably the simplest and most intuitive solution (since pasting in text with multiple lines is already possible, so users may be familiar with a similar process)

**Comment by towerofnix** [comment]
> Alternatively, it could insert one line at a time, then automatically submitting when it encounters a newline character, kind of like the command prompt when I paste in multiple commands separated by newlines). This would help with importing from a text file exported from a list, though I suppose they could just drag and drop into the list since that'll also be added.

I'm hesitant about this, since it's not really something users *without* the addon would ever be expected to do. If they need to import multiple lines, that's what lists are for, and that's already something Scratch-native can do, since importing lists is a valid option :P

Good point re: browsers automatically stripping them though! I kinda forgot you can totally just paste multiple lines of text into a prompt input already.

As for fancy UI, I thiiink that's best kept to #1990, which is kinda all about having a specific UI for importing data. I wouldn't want this addon to accidentally conflict with (or add way more mostly unneeded complexity on top of) that one! :P
