### ISSUE TITLE
"Show my-ocular status" addon has outdated name and description

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2060]
**Describe the bug**

The name and description of the `my-ocular` addon are outdated.

**Expected behavior**

The name should say "ocular status", not "my-ocular status", and the description should contain the new link for setting the status: https://ocular.jeffalo.net/dashboard

**Comment by jeffalo** [comment]
i was planning on updating it alongside some additions like showing ocular reaction counts and stuff. still thinking on how to safely integrate it on ocular's end but keep it seemless.

**Comment by RedGuy12** [comment]
It'd have to be re translated
________________________________
From: Maximouse ***@***.***>
Sent: Saturday, April 3, 2021 2:47:56 AM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] "Show my-ocular status" addon has outdated name and description (#2060)


Describe the bug

The name and description of the my-ocular addon are outdated.

Expected behavior

The name should say "ocular status", not "my-ocular status", and the description should contain the new link for setting the status: https://ocular.jeffalo.net/dashboard

**Comment by mxmou** [comment]
@RedGuy12 True, but I don't think that's an issue.
