### ISSUE TITLE
Button to unshare projects in the editor

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2075]
**Describe the new addon**

Button to unshare projects in the editor because every single time we have to go to my stuff and unshare it.

**Comment by RedGuy12** [comment]
Yes! It could replace the "Shared" notice.
________________________________
From: 9gr ***@***.***>
Sent: Sunday, April 4, 2021 1:01:27 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Button to unshare projects in the editor (#2075)


Describe the new addon

Button to unshare projects in the editor because every single time we have to go to my stuff and unshare it.

**Comment by Endermaster3690** [comment]
> Yes! It could replace the "Shared" notice.

Great idea!

**Comment by SheepTester** [comment]
While at it, it might be nice to re-add the [recently removed](https://scratch.mit.edu/discuss/topic/46779/) share button in the mystuff page

**Comment by jeffalo** [comment]
> recently removed

> July 23, 2014
