### ISSUE TITLE
Alpha (Opacity) slider in costume editor.

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#2129]
Currently, there are only color, brightness and saturation sliders in the color picker. I suggest adding a new one for alpha (or opacity). In vanilla scratch the only way to get semi-opaque pixels is using bucket fill option and selecting a gradient between no color and a fully opaque color. This creates major headaches if you want a large section of the same opacity as you have to copy the pixel that has the opacity you want to create a large section of those pixels.

An example of opacity in the costum editor created with the bucket fill gradient method.
![image](https://user-images.githubusercontent.com/27910867/114293138-09eb6500-9ad7-11eb-9ea6-d54c4c592fbc.png)

**Comment by SheepTester** [comment]
Hmm, I've tried this before

The existing colour picker addons simulate a colour picker selecting a specific colour, but this only works for opaque values

I think I tried messing with redux a bit, but it seems scratch-paint explicitly checks for [valid 6-digit hex colours](https://github.com/LLK/scratch-paint/blob/develop/src/lib/make-color-style-reducer.js#L47) (i.e. no transparency)

However, I know that with imported SVG costumes, the colour picker does support transparency when you select a shape with a translucent stroke/fill, so maybe not all hope is lost?

**Comment by TheColaber** [comment]
@SheepTester Not all hope is lost, because scratch does support transparent SVGs. In fact, I was able to create my own, from selecting a shape in a costume, and changing its properties through Redux. And in the "scratch-paint/select/CHANGE_SELECTED_ITEMS" event, you will get a `selectedItems` array. And... As you can see, it has tons of things that we can edit...
![image](https://user-images.githubusercontent.com/72760579/114302866-0802b100-9a99-11eb-8005-3b43a02cb5b6.png)
I once remembered seeing a transparency value, so let's see where that is...
![image](https://user-images.githubusercontent.com/72760579/114302937-6891ee00-9a99-11eb-8a79-c7379f059536.png)
And look what we have here...
![image](https://user-images.githubusercontent.com/72760579/114302947-70ea2900-9a99-11eb-8946-e06bc7e4e21a.png)
![image](https://user-images.githubusercontent.com/72760579/114302954-7e071800-9a99-11eb-870d-53468b3a5983.png)
So it's actually quite simple, but the hard part, is getting the UI right... Before when I was trying to make this addon... I had all the code down, but the UI was just an input that get's appended to the screen where the rest of the tools are. So maybe there is a better way? But an input would also work...

**Comment by Tacodude7729** [comment]
So it's not possible to set your pen color in bitmap mode to something transparent? I don't know much about redux but is it not possible to change the state required without going through the scratch reducer? It's a shame, I mainly wanted this for use with bitmap.

**Comment by TheColaber** [comment]
> So it's not possible to set your pen color in bitmap mode to something transparent? I don't know much about redux but is it not possible to change the state required without going through the scratch reducer? It's a shame, I mainly wanted this for use with bitmap.

I wish it was that easy, but scratch checks the values set before drawing and removes an opacity it sees.

**Comment by SheepTester** [comment]
Bitmap does have rudimentary support for transparency it seems; just not for strokes

<img src="https://cdn.discordapp.com/attachments/775797057926856754/831567153194598460/THE_GIF.gif" width="540.5">

I think this is fine since the fill tool works, but users might continually report the behaviour of the pen etc. as a bug

**Comment by Hans5958** [comment]
For the record: This suggestion is highly anticipated. Hundreds of (duplicate) website feedback, Discord suggestions, Scratch comments have already been made. This suggestion is amplified that it is already implemented in TurboWarp.
