### ISSUE TITLE
60 FPS Sticky Toggling

### ISSUE THREAD

**Issue by DogCatPuppyLover** [ScratchAddons/ScratchAddons#2153]
**Describe the bug**

When you alt + click the green flag on a Scratch project and have the 60 FPS addon enabled, 60 FPS is toggled. However, once the alt key is no longer being pressed, it often still toggles 60 FPS instead of restarting the project when you click the green flag. This continues for an unpredictable number of times until it restarts the project like it's supposed to.

**To Reproduce**

1. Go to any Scratch project
2. Hold down the alt key and click on the green flag.
3. Stop pressing the alt key and click again.
5. Eventually, if you click enough, it'll do what it's supposed to do, which is restart the project.

**Expected behavior**

When the alt key is not pressed, clicking the green flag should not toggle 60 FPS.

**Screenshots**

https://user-images.githubusercontent.com/79656307/114634969-997c4980-9c78-11eb-93dc-6edf62d25855.mp4

(note that I pressed the alt key for the first time I pressed the green flag in the upper left, but not any of the other clicks)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Chrome version 89.0.4389.114

**Additional context**

To work around this bug, you can toggle 60 FPS and then open full screen mode. You can restart the project without the undesired FPS toggling. However, the bug remains when you go back to small screen.

**Comment by RedGuy12** [comment]
cc @jeffalo
________________________________
From: Isla ***@***.***>
Sent: Tuesday, April 13, 2021 6:57:29 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] 60 FPS Sticky Toggling (#2153)


Describe the bug

When you alt + click the green flag on a Scratch project and have the 60 FPS addon enabled, 60 FPS is toggled. However, once the alt key is no longer being pressed, it often still toggles 60 FPS instead of restarting the project when you click the green flag. This continues for an unpredictable number of times until it restarts the project like it's supposed to.

To Reproduce

  1.  Go to any Scratch project
  2.  Hold down the alt key and click on the green flag.
  3.  Stop pressing the alt key and click again.
  4.  See error
  5.  Eventually, if you click enough, it'll do what it's supposed to do, which is restart the project.

Expected behavior

When the alt key is not pressed, clicking the green flag should not toggle 60 FPS.

Screenshots

https://user-images.githubusercontent.com/79656307/114634969-997c4980-9c78-11eb-93dc-6edf62d25855.mp4

Device (please complete the following information):

  *   OS: Windows 10
  *   Browser: Chrome
  *   Chrome version 89.0.4389.114

Additional context

To work around this bug, you can toggle 60 FPS and then open full screen mode. You can restart the project without the undesired FPS toggling. However, the bug remains when you go back to small screen.

**Comment by jeffalo** [comment]
this has something to do with the chromeos compatibility @WorldLanguages added. it worked fine previously, but now it is unpredictible

**Comment by WorldLanguages** [comment]
We should be able to decrease the timeout delay

**Comment by xItzDiamondx** [comment]
Should be a setting

**Comment by xItzDiamondx** [comment]
Or @WorldLanguages, we could detect if the flag was clicked again, that way, 60 FPS would be turned off. In the extension setting page, there should be a option saying "Sticky 60 FPS".
