### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#220]
**Is your feature request related to a problem? Please describe.**

so basically, i think i came up with a great solution to a problem im sure no one has thought of yet.

when there are a bunch of entire site redesigning userstyles, there's going to be the issue of having multiple userstyles that won't work well together

**Describe the solution you'd like**

userstyles that basically redesign scratch should be implemented in the "Themes" menu, and you can only have one selected at once.

**Describe alternatives you've considered**

forcing all themes to be compatible

**Additional context**

im sure this was probably the plan but i think it would be nice to have a discussion about this

**Comment by Explosion-Scratch** [comment]
Only one at once?! No!!! It's Waay better to make gthem compatible with each other so that users can use dark mode and nice forum buttons or deleted comments and dark mode. It's well worth fixing these issues to have an addon that works super well and totally customizes scratch. Another alternative is warning users when they try to activate more than one. They can then continue or stop if they want.

**Comment by WorldLanguages** [comment]
I just made 2 themes (and 2 non-themes) compatible, took a little bit of work, but not that much. Check the latest PR/commit.
