### ISSUE TITLE
Scratch Addons isn't working

### ISSUE THREAD

**Issue by GordoiteYT** [ScratchAddons/ScratchAddons#2393]
I installed the Addons and 8 months later idk why but the extentions are broken, and the setting screen isn't working, any help?

**Comment by TheColaber** [comment]
This does not tell us anything. What exactly is broken? How can we repro?

**Comment by GrahamSH-LLK** [comment]
Hi! To properly find the cause of this bug, could you go to chrome://extensions, enable developer mode, and click on the "errors" on our extension? Then, can you take a screenshot or copy them here?

**Comment by GordoiteYT** [comment]
how can I do that?

**Comment by GordoiteYT** [comment]
how can I do that?

**Comment by GrahamSH-LLK** [comment]
Easier version: go to settings page, inspect, send errors

**Comment by lisa-wolfgang** [comment]
@GordoiteYT
1. Enter "chrome://extensions" in your URL bar

![image](https://user-images.githubusercontent.com/43426138/117206280-464d7080-adb8-11eb-846d-fe08d8b6522e.png)

2. Toggle the "Developer mode" switch in the upper-right hand corner

![image](https://user-images.githubusercontent.com/43426138/117206815-ec00df80-adb8-11eb-8c76-03db914595a2.png)

3. Find the Scratch Addons card and click "Details"

![image](https://user-images.githubusercontent.com/43426138/117206963-105cbc00-adb9-11eb-9109-c4120241d1c1.png)

4. Scroll down and find the "Collect errors" option, then switch it on.

![image](https://user-images.githubusercontent.com/43426138/117207069-28ccd680-adb9-11eb-9e4c-77ed72a93e91.png)

5. Try to use Scratch Addons as normal. If something weird happens, go back to this page and click the "Errors" button:

![image](https://user-images.githubusercontent.com/43426138/117207321-76e1da00-adb9-11eb-8cd7-9476c1c2f8ac.png)

Then take a screenshot of the messages that appear. Note that it's normal to have one error because of a Chrome issue with Firefox-only properties.

**Comment by GordoiteYT** [comment]
Firstly, thatnks @lisa-wolfgang for helping me.
 Secondly, here are my errors that "broke" the extention.
![errors](https://user-images.githubusercontent.com/79427718/117210401-3ab07880-adbd-11eb-8b6c-bacb88dde543.png)

**Comment by RedGuy12** [comment]
> Firstly, thatnks @lisa-wolfgang for helping me.
> Secondly, here are my errors that "broke" the extention.
> ![errors](https://user-images.githubusercontent.com/79427718/117210401-3ab07880-adbd-11eb-8b6c-bacb88dde543.png)

Can you expand the bottom two?

**Comment by GordoiteYT** [comment]
Sorry!, there they are.

**Comment by apple502j** [comment]
Please update your browser.

**Comment by GordoiteYT** [comment]
dang.

**Comment by GordoiteYT** [comment]
I can't even update my broswer -_-.

**Comment by GordoiteYT** [comment]
> Please update your browser. At least Chrome 81, but use the latest for security!

Ok, im using a chromebook (yep its crappy) and it is version 76, and if I check for updates it says "You are up to date!" so what should I do now? I can't update chrome.

**Comment by GrahamSH-LLK** [comment]
> > Please update your browser. At least Chrome 81, but use the latest for security!
> 
> Ok, im using a chromebook (yep its crappy) and it is version 76, and if I check for updates it says "You are up to date!" so what should I do now? I can't update chrome.

Your chromebook must have reached its EOL for updates.

**Comment by WorldLanguages** [comment]
If you really want to, you could try checking where the error exactly happens and see if you can use a JavaScript compiler like Babel to make it work on your older Chrome version. But don't expect us to support any browser version older than 6 months

**Comment by GordoiteYT** [comment]
> If you really want to, you could try checking where the error exactly happens and see if you can use a JavaScript compiler like Babel to make it work on your older Chrome version. But don't expect us to support any browser version older than 6 months

can't, im too dum to use java.

**Comment by CubeyTheCube** [comment]
> > If you really want to, you could try checking where the error exactly happens and see if you can use a JavaScript compiler like Babel to make it work on your older Chrome version. But don't expect us to support any browser version older than 6 months
> 
> can't, im too dum to use java.

java isnt javascript

**Comment by GordoiteYT** [comment]
what is it then?
