### ISSUE TITLE
New Microsoft Edge

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#241]
As far as I know, the new (Chromium) Microsoft Edge will work with this extension. We should mention this in the documentation.

**Comment by JeffaloBob** [comment]
technically all chromium browsers should work

**Comment by Hans5958** [comment]
If an app works on Chrome, then it automatically works on all Chromium-based browser. From Vivaldi, Brave, Opera, the new Edge, even that weird Opera GX thing.

In the README, I only listed the Chrome steps for Chrome only because I can't guarantee that the same steps applies to those browser. But, if it ready for release, then of course it will be mentioned in the README, and hopefully the website. As long, Exploding didn't forget to put one.

**Comment by WorldLanguages** [comment]
Well, should we? I believe anyone that downloads a Chromium browser knows Chrome Web Store extensions will work. I've been using Brave to develop the extension all this time, but I don't think that it deserves a mention in the docs, since Brave doesn't have its own extension store, and even if it had, I don't think we'd be interested on publishing the extension on it.

**Comment by Hans5958** [comment]
> I believe anyone that downloads a Chromium browser knows Chrome Web Store extensions will work.

Tell that to the kids. Apparently, even some grown ups didn't know that you can do that and keep asking if the extension works with Opera GX.

**Comment by Hans5958** [comment]
I thought your point is "it's a public knowledge that Chrome extensions works with other Chromium-based browser."

**Comment by JeffaloBob** [comment]
> > I believe anyone that downloads a Chromium browser knows Chrome Web Store extensions will work.
> 
> Tell that to the kids.
> 
> Apparently, even some grown ups didn't know that you can do that and keep asking if a Chrome extension works in Opera GX.

![image](https://user-images.githubusercontent.com/40470736/92626481-426d5b00-f2ca-11ea-9404-b983266d5b95.png)

**Comment by wgyt735yt** [comment]
> > > I believe anyone that downloads a Chromium browser knows Chrome Web Store extensions will work.
> > 
> > 
> > Tell that to the kids.
> > Apparently, even some grown ups didn't know that you can do that and keep asking if a Chrome extension works in Opera GX.
> 
> ![image](https://user-images.githubusercontent.com/40470736/92626481-426d5b00-f2ca-11ea-9404-b983266d5b95.png)

Chromium-based browsers all support chrome extensions, but some platform-specific features won't work on other platforms.
That was a lot to say, now I need a drink. lttstore.com
