### ISSUE TITLE
Ability to perm delete specific project

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#2423]
There is only one button, delete all. Should there be an (x) button on all the projects (top right) when you glide your mouse on it? So you could perm delete only one project.

**Comment by GrahamSH-LLK** [comment]
> There is only one button, delete all. Should there be an (x) button on all the projects (top right) when you glide your mouse on it? So you could perm delete only one project.

What are you talking about?

**Comment by Shluffy** [comment]
> There is only one button, delete all. Should there be an (x) button on all the projects (top right) when you glide your mouse on it? So you could perm delete only one project.

I'd say yes, maybe perm deleting would be nice. From the background though, is that actually possible if you have multiple projects in trash? or would it then perm delete all of them with the one you want.

**Comment by Shluffy** [comment]
> > There is only one button, delete all. Should there be an (x) button on all the projects (top right) when you glide your mouse on it? So you could perm delete only one project.
> 
> What are you talking about?

I think they mean being able to permanently delete a project on it's own, and skip sending it to trash, just perm delete it all at once.

**Comment by mxmou** [comment]
I don't think Scratch has an API for removing a specific project from the trash.

**Comment by retronbv** [comment]
> I don't think Scratch has an API for removing a specific project from the trash.

It has to have an api for it if you can remove from trash. Right?

**Comment by mxmou** [comment]
> > I don't think Scratch has an API for removing a specific project from the trash.
> 
> It has to have an api for it if you can remove from trash. Right?

Emptying the trash deletes all projects.

**Comment by Shluffy** [comment]
> > > I don't think Scratch has an API for removing a specific project from the trash.
> > 
> > 
> > It has to have an api for it if you can remove from trash. Right?
> 
> Emptying the trash deletes all projects.

so at this point the addon is impossible to make?

**Comment by retronbv** [comment]
Ah, I thought that you could delete a certain one. My fault

**Comment by Shluffy** [comment]
So close this?

**Comment by retronbv** [comment]
> So close this?

I don’t have perms to, sorry

**Comment by mxmou** [comment]
This is actually possible - Scratch's code for restoring a project from trash looks like this:

<img width="747" height="68" alt="Image" src="https://github.com/user-attachments/assets/3de76762-9bc1-49bc-b22f-f21a573400e8" />

Doing the same thing with a `visibility` of `"delbyusr"` instead of `"visible"` deletes the project permanently. I tried sending the request using the browser console and it worked:

<img width="1101" height="30" alt="Image" src="https://github.com/user-attachments/assets/d5547e3c-e7f5-4f55-9e51-e247580e2dd9" />

<img width="700" height="73" alt="Image" src="https://github.com/user-attachments/assets/76401c8e-efd6-4b27-8cc8-9e300873c01d" />
