### ISSUE TITLE
API for low-level observing & mutating overridden prototype calls

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#243]
**Is your feature request related to a problem? Please describe.**

ScratchAddons provides various APIs for interacting with the Scratch website and editor, allowing for a variety of features and tweaks to be implemented without having to interface with low-level aspects of hacking webpages through JS. However, this leaves addon developers in a position where if a *new* interface is required, it must be implemented as an abstraction alongside the existing API; particularly, modifying `content-scripts/prototype-handler.js` is necessary. Thus, addons which require new ways of interacting with the website *must* make additional changes to the internal code, and this is not ideal (the code impact of API changes is weighted greater than simply creating a new addon).

**Describe the solution you'd like**

A new, general-purpose interface should be added to `addon.tab.traps` for interacting with the low-level prototype overrides whenever an addon developer deems it necessary or practical. The particular implementation I've created and am requesting here would allow for both observing and mutating the arguments passed to overridden prototype functions; this would allow the greatest variety of uses while keeping API complexity minimal. See the pull request #244 for specific implementation details.

**Describe alternatives you've considered**

The obvious alternative is to simply implement new interfaces when a new feature is desired. Technically speaking, this *works*, but it implicates frequently modifying and expanding the API, and as mentioned that isn't ideal. The solution I've proposed is general-purpose - no more API modifications are necessary.

Of course, there may be cases where modifying the API *is* appropriate, e.g. implementing more state. This request doesn't make it harder to implement those; all the existing code works. It simply allows addon developers to decide for themselves whether or not expanding the API would be ideal for their addon.

Moreover, the proposed solution (alongside the implementation shared in #244) allows for much more direct interception of code than is properly supported. This is practical, as in cases like intercepting reducer state, where what's wanted really is to simply override `Object.assign` - this API would allow doing so in a very clean and concise manner.

**Additional context**

The idea for this came to mind while working on a "separate Lists category" addon; I wanted to intercept the reducer which handles scratch-blocks toolbox XML data, but it didn't seem like adding a whole new fake state manager (not to mention a way of *mutating* state) for the one addon was worthwhile. So I looked to see if a more general solution could be made, and that became this issue (and the corresponding pull request, #244).

**Comment by apple502j** [comment]
Well, for state handled by Redux we have the state and the familiar `dispatch` function available. You can for example `addon.tab.traps.dispatch({type: 'scratch-gui/toolbox/UPDATE_TOOLBOX', toolboxXML})`.

I first wanted to make the stuff customizable by `addon.json` - but there are some problems with it. Obviously the injected scripts cannot read such files, so we need to have it read by the background, but that's going to be async operation - and injecting prototype must be sync operation because we can't have Scratch GUI execute further and operate on clean prototypes. The injection script is also executed at `document_start`, which means not all DOM is complete - while it's fine for some stuff (and definitely required), the way we communicate between privileged API and website's injected script is by using DOM, so there is no guarantee that it works. It may be possible to do the stuff when we create the string for injection, but haven't tried it yet, so it may be an option.

I've never thought the arguments as something we manipulate - prototype-handler was always read-only, partly because most of the trapped ones are objects which can be modified.

- Looking at the PR, it seems like this is not as serious as I thought :P
