### ISSUE TITLE
Editor dark mode: "ask and wait" questions ran by stage are unreadable

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2433]
Only happens when the stage uses the "ask and wait" block.
Sprites use the same bubble as "say" block to show what's being asked.

![image](https://user-images.githubusercontent.com/17484114/117517083-43e24680-af71-11eb-9fff-7d4e55c7ae83.png)

**Comment by Endermaster3690** [comment]
probably fixable with the question backgrounds being black

**Comment by mxmou** [comment]
@Endermaster3690 The text should be black, see #2241.

**Comment by Endermaster3690** [comment]
> @Endermaster3690 The text should be black, see #2241.

i know but with the website dark mode or whatever i think the background should be black.

**Comment by TecFuture** [comment]
Change the text color when aking answer? or give change code for this specific function?

At wednesday EST 3:00 PM(5/10/2021), I was presenting a project to my math club which was worked on for a few months by me and my friend, I noticed right before I was presenting screen that scratch addons updated. I simply accepted and moved on.

The project uses [Ask ()] function to tell the math problem which is main, Unfortunately the text wasn't readable and I knew it was because of the update, so I had to disable scratch addons in mid-presentation ... 

Even when I am testing this glitch forces me to turn of night-mode which is one of my favorite things about scratch addons.
So for me I have urgency for this problem to be resolved
