### ISSUE TITLE
Link to quoted post

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2468]
**Is your feature request related to a problem? Please describe.**

Scratch doesn't provide an easy way to jump to the quoted post from a quote.

**Describe the solution you'd like**

An option in the Better quoter addon to automatically add a link when quoting a post.

**Describe alternatives you've considered**

It could also be its own addon.

**Comment by CST1229** [comment]
Here's my idea for it:
If you put [quotepost=postid][/quotepost] at the start of the inside of a quote, then the addon would make the quote link to that post. That addon would automatically add that tag to quotes.
Could possibly use some sort of prefix to distinguish it from official tags ("ex-" maybe? definitely not "sa-" because the policy).

**Comment by RedGuy12** [comment]
It could do something like this:
```bbcode
[quote][link=<link>][b]<person> wrote:[/b][/link]
<post>
[/quote]
```
Or should it be:
```bbcode
[quote][b]<person> wrote:[/b]
<post>
[small]([link=<link>]source[/link])[/small]
[/quote]
```

**Comment by CST1229** [comment]
I previously made a bookmarklet that does this, in that the BBCode for quoting is like this:
```
[quote=<user>]<post>
[url=scratch.mit.edu/discuss/post/<postid>][small][i][color=#888888][[]Original post][/color][/i][/small][/url][/quote]
```
