### ISSUE TITLE
Addon Ideas

### ISSUE THREAD

**Issue by Jariel208** [ScratchAddons/ScratchAddons#2624]
Hello! So, for some reason, there should be addons that are the rest of the features from TurboWarp added to Scratch Addons, such as "While ( )", "For each ( ) in ( )" and other blocks, opacity in Paint Editor, infinite clones mode, etc. You should also put an addon where you can put custom blocks to categories, and when people have SA, they will see custom blocks on different categories, otherwise the custom blocks will be in the "My Blocks" category.

Hope you add those addons I planned you!

- Respect, Jariel

**Comment by mxmou** [comment]
Adding new block or other features that would allow people to make projects that don't work without Scratch Addons is rejected.

**Comment by RedGuy12** [comment]
Please only one addon/issue.

Please use the search bar to find duplicates. (There are)

We can't add many features from TurboWarp (in this case opcatiy) i because they can modify the internal workings of Scratch, while we can only run code on top of Scratch.

The clone limit is there for a reason: so people's computers don't crash.

**Comment by RedGuy12** [comment]
Please only one addon/issue.

Please use the search bar to find duplicates. (There are)

We can't add many features from TurboWarp (in this case opcatiy) i because they can modify the internal workings of Scratch, while we can only run code on top of Scratch.

The clone limit is there for a reason: so people's computers don't crash.

**Comment by Jariel208** [comment]
it's okay tho

**Comment by return-misaPuding** [comment]
The "while()" block exists in vanilla Scratch, it's just hidden.
@GarboMuffin can confirm this.

Dne st 26. 5. 2021 21:47 uživatel Maximouse ***@***.***>
napsal:

**Comment by Jariel208** [comment]
I WANNA FIND THAT HIDDEN BLOCK LOL
poggers
