### ISSUE TITLE
Scratch Homepage Dark-Theme

### ISSUE THREAD

**Issue by Platinum-Phoenix** [ScratchAddons/ScratchAddons#263]
So, how do you think this looks so far before I do a PR. 
<img width="1440" alt="Screen Shot 2020-09-11 at 9 52 30 AM" src="https://user-images.githubusercontent.com/54418727/92933657-83718680-f414-11ea-9506-7ff1bb277eef.png">

**Comment by towerofnix** [comment]
I like it, but I think it could use some adjustments depending on the goal of this style - what do you feel the purpose of a dark theme is? To me, it's to reduce the strain of the screen on my eyes, and to make elements of the user interface I care about (e.g. Scratch blocks) stand out better against the background and less important elements around it. In that regard, I'd suggest that the backdrop of the page could be a darker gray (most dark themes I've seen go darker than the midtones you're using), and the borders of the rows ("Featured Studios" etc) could be darkened as well, to a lower contrast gray which doesn't make the borders stand out so much. (After all, the borders are not the element I want to focus on - the content of the slider is!)

It's possible you have a different goal/purpose for your dark theme, in which case my suggestions might not be applicable. My general tip is that whenever you're writing a userstyle, it will help a lot to figure out a specific goal and keep it in mind, so that you can use it to guide decisions on how to make the style reach that goal better.

**Comment by Platinum-Phoenix** [comment]
Thanks for the feedback. I guess my thought process is that important things (like the projects) I think I agree with what you are saying so, I will try and implement it.

**Comment by GrahamSH-LLK** [comment]
Something's wrong with the navbar. It's too tall. You probably messed with it's height; it should be 50px

**Comment by Platinum-Phoenix** [comment]
@GrahamSH-LLK No that was just the color of my bookmarks bar in my browser.

Also here is my new progress:

<img width="1437" alt="Screen Shot 2020-09-12 at 11 33 24 AM" src="https://user-images.githubusercontent.com/54418727/92999036-c6eaf400-f4eb-11ea-8d73-da63ba1aa9ba.png">

**Comment by GrahamSH-LLK** [comment]
It could use some brightening up. Maybe a lighter shade for the background?

**Comment by GrahamSH-LLK** [comment]
We already have 2 dark mode addons coming. If you're still doing this, then tell me and I'll reopen this.
