### ISSUE TITLE
Scratch Messaging UI is displayed in extension popup even though I have that addon disabled

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#267]
**Describe the bug**

I have the Scratch Messaging addon disabled, but the UI for it displays anyway! It's empty (no message content), but the buttons to mark messages as read, pop the screen into a new tab, etc all display.

**To Reproduce**

1. Make sure the Scratch Messaging addon is disabled.
2. Click on the Scratch Addons extension icon.
3. Note that the UI for Scratch Addons is still displayed.

**Expected behavior**

It shouldn't display, because the addon is disabled, implying the user does not want or expect to see effects of the addon.

**Device (please complete the following information):**

- OS: Debian (Linux)
- Browser: Firefox (Developer Edition)
- Version: 81.0b

**Comment by WorldLanguages** [comment]
If you wait ~2 seconds you should get this, can you reproduce?
![image](https://user-images.githubusercontent.com/17484114/92999326-657c5280-f4f6-11ea-96f2-4516a3c95bb7.png)

**Comment by towerofnix** [comment]
@WorldLanguages Nope, nothing. It's just blank (and the buttons at the bottom stay there).

IMO the ideal result would be one which doesn't advertise that addon whenever opening the extension popup, since whether a user decides to use the addon or not is a conscious decision. (A "dismiss" button to hide the UI might be the best of both worlds.)

**Comment by WorldLanguages** [comment]
Oh right Firefox, let's see why you act differently than Chrome this time...

**Comment by WorldLanguages** [comment]
Well I have to admit Firefox isn't entirely wrong. Pushing a fix...
@towerofnix Keep in mind that I'm discussing with griffpatch the possibility of updating Scratch Messaging Extension in the store with Scratch Addons, in that case showing the popup for Scratch Messaging even if it's disabled makes some sense, since it's theoretically the same extension but "upgraded". Of course, Scratch Messaging will be enabled by default, but if a user accidentally disables it, it will be easy to know how to re-enable it. As long as no other addons require the space in the extension popup this will probably stay like this.
