### ISSUE TITLE
scratch-messaging should not have background script

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2703]
see also #1662

if we truly need to send the request from background, we can just make a proxy script that only triggers from our own popups.

**Comment by WorldLanguages** [comment]
Marking messages as read should be done through an iframe instead of using `?sareferer` as well.

**Comment by WorldLanguages** [comment]
Note, the messages array should be cached in a persistent script. This is about moving logic that has no reason at all to be there.

**Comment by apple502j** [comment]
How should it cache? Like message id to message object?

**Comment by WorldLanguages** [comment]
It already "caches". It stores all the message objects for unread messages (up to a limit) all the time so that they're ready.
This could be extended to cache specific comment contents as well. I think parent comment contents could be cached, so the only thing we'd need to check is if it got any replies.

**Comment by apple502j** [comment]
Not a bug; rather a tech debt.

**Comment by apple502j** [comment]
Updates:

- iframe does not work due to SameSite cookies
- We have to pop a new window for this
