### ISSUE TITLE
[gamepad]: Ability to export controller settings

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2752]
> Ability to export controller settings (json maybe).

**Comment by GarboMuffin** [comment]
What is the use case for this?

If it's for project creators to override default settings because they think they're smarter than the addon, then the new (not yet released) "Store these settings in the project to override the default configuration (Experimental tool for project creators)" checkbox in the settings modal is what they should use.

**Comment by TheColaber** [comment]
good point, i forgot you added that

**Comment by WorldLanguages** [comment]
> What is the use case for this?

@GarboMuffin See new issue #7045, it could be useful if the creator didn't add the preset or "if you want your own control scheme"

**Comment by OneShot-Niko** [comment]
> See new issue #7045, it could be useful if the creator didn't add the preset or "if you want your own control scheme"

By the "your own control scheme" part I meant that as in not needing to default to the project or manually redoing the controls, not making own presets
(Apologies if im misinterpreting what you mean here)
