### ISSUE TITLE
Bring addon changes from TurboWarp

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2800]
I'll do it this weekend probably. Most do not matter, but some might.

- [ ] 2d-color-picker/paint-editor.js L240: use array destructing
- [ ] block-switching/userscript.js L3: wait until blockly is available
- [x] blocks2image/userscript.js L199
- [x] clones/userscript.js L19 displayNoneWhileDisabled
- [ ] L45 fallback for larger clone count (might happen in vanilla because of a bug)
- [x] L48
- [ ] custom-zoom/userscript.js L2: await getblockly
- [x] drag-drop/dragged-over.css L14: style changes
- [x] editor-colored-context-menus/userscript.css L2: !important
- [ ] editor-devtools/DevTools.js L2258: noreferrer/noopener (no sec risks, because noopener and referrer-policy: sowco is default)
- [ ] DomHelpers.js L87: removed logging
- [ ] userscript.js L50: noopener noreferrer
- [x] fix-share-the-love/userscript.js L3: get blockly and dispatch resize event (this is to hack blockly, right?)
- [x] editor-theme3/theme3.js L50: change injection point
- [ ] hide-flyout/userscript.js L73: redux condition
- [x] mediarecorder/style.css L44: new style for text color
- [x] mediarecorder/userscript.js L43: Safari supports MP4 but not WebM. Maybe param it?
- [ ] mute-project/userscript.js L5: lazyload image

@GarboMuffin Are there any that should not be imported?

**Comment by GarboMuffin** [comment]
`2d-color-picker/paint-editor.js L240: use array destructing` - all my 2d color picker changes were for compatibility with transparency, but they probably dont hurt
`block-switching/userscript.js L3: wait until blockly is available` - probably ok
`blocks2image/userscript.js L199` - not needed (my scratch-blocks tries to hide offscreen things)
`clones/userscript.js L19 displayNoneWhileDisabled` - is caused by my displayNoneWhileDisabled working different than yours, not needed and probably breaks SA
`L45 fallback for larger clone count (might happen in vanilla because of a bug)` - ok
`L48` - is caused by my displayNoneWhileDisabled working different than yours, not needed and probably breaks SA
`custom-zoom/userscript.js L2: await getblockly` - probably ok
`drag-drop/dragged-over.css L14: style changes` - no, that makes the highlight red, which you probably don't want
`editor-colored-context-menus/userscript.css L2: !important` - maybe? this is for compatibility with my dark mode. Might fix #2644
`editor-devtools/DevTools.js L2258: noreferrer/noopener (no sec risks, because noopener and referrer-policy: sowco is default)` - I target some older browsers where those tags might actually mean something, you might not care much
`DomHelpers.js L87: removed logging` - ok
`userscript.js L50: noopener noreferrer` - I target some older browsers where those tags might actually mean something, you might not care much
`fix-share-the-love/userscript.js L3: get blockly and dispatch resize event (this is to hack blockly, right?)` - I think it might've been to make sure that the stage updates its bounding client rect so that mouse events works properly? Really not sure. I don't think that would affect you because SA reliably injects CSS very early unless I'm mistaken
`editor-theme3/theme3.js L50: change injection point` - not necessarily needed, I changed it for compatibility with my different CSS injection point
`hide-flyout/userscript.js L73: redux condition` - sure
`mediarecorder/style.css L44: new style for text color` - for compatibility with my dark mode, probably not needed
`mediarecorder/userscript.js L43: Safari supports MP4 but not WebM. Maybe param it?` - don't bother, Safari's mp4 support is basically unusable. that's all dead code right now
`mute-project/userscript.js L5: lazyload image` - sure

**Comment by mxmou** [comment]
> `editor-colored-context-menus/userscript.css L2: !important` - maybe? this is for compatibility with my dark mode. Might fix #2644

It would fix #2644, but not the right way (the border and text should be colored, not the background.
