### ISSUE TITLE
A beta addon is enabled by default

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2863]
The "Studio manager tools" addon (which is marked as beta) is currently enabled by default.
This is most likely intended for easier development, but I thought it would be a good idea to create an issue for it so it doesn't slip off our radar.

**Comment by RedGuy12** [comment]
It's only marked as beta because there may be bugs with the new studio page. Probably not, but it's possible as we haven't been testing after every single PR on llk/scratch-www
________________________________
From: lisa-wolfgang ***@***.***>
Sent: Tuesday, June 22, 2021 8:38:22 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] A beta addon is enabled by default (#2863)


The "Studio manager tools" addon (which is marked as beta) is currently enabled by default.
This is most likely intended for easier development, but I thought it would be a good idea to create an issue for it so it doesn't slip off our radar.

**Comment by apple502j** [comment]
This is temporary; no need to mess with the configurations.

**Comment by mxmou** [comment]
This wouldn't be a problem (the beta label will likely be removed after new studios launch) if it didn't make the addon show at the beginning of the list of addons. Maybe that feature could be disabled for this specific addon?

**Comment by apple502j** [comment]
Well, the update already dropped, and I'm sure if the Scratch Team does not lie, the next SA update is after the studio update...

**Comment by WorldLanguages** [comment]
> This wouldn't be a problem (the beta label will likely be removed after new studios launch) if it didn't make the addon show at the beginning of the list of addons. Maybe that feature could be disabled for this specific addon?

I find that a good feature, if for some reason our addon breaks new studio pages when they launch, users will easily find the culprit I guess :P
