### ISSUE TITLE
[Feature Request] load experimental

### ISSUE THREAD

**Issue by YOYITsM3M8** [ScratchAddons/ScratchAddons#287]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**

Add it so you can load a addon folder and it be experimental from the options page.
**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by JeffaloBob** [comment]
as in, custom addons? i feel like adding this could get the extenstion rejected by the stores.

maybe if it's called something like developer mode options and hidden deep somewhere it might fly past but better be careful

**Comment by WorldLanguages** [comment]
There's no way to achieve this without making a forked version of the extension with a less strict CSP

**Comment by GrahamSH-LLK** [comment]
Why? All it needs to do is upload a file, and use localstorage to save it.

**Comment by WorldLanguages** [comment]
Well, it would work but only for userstyles. Scripts are ran with dynamic `import()` which only accepts URLs :P

**Comment by Explosion-Scratch** [comment]
@WorldLanguages would it work to ony import via url? (e.g. from a github gist or something)

**Comment by WorldLanguages** [comment]
@Explosion-Scratch Any URL would work, technically we could add a way so that uploaded files go to the "cloud" to then be imported through a URL, but that's a bit too extreme :P Keep in mind the fact Scratch Addons is split in "addons" is to enable open source collaboration - Scratch Addons isn't an addon manager. Those are Tampermonkey and Stylus.
