### ISSUE TITLE
Studio Update Megathread

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2917]
All of them are being worked on by me. Please edit in case you found issues:

- [ ] infinite-scrolling does not support projects
- [ ] infinite-scrolling does not support browse projects
- [ ] infinite-scrolling does not support curator/manager
- [ ] more-links crashes
- [ ] scratch-messaging does not handle reply limit
- [ ] studio-tools promoter/remover input remains disabled after error
- [ ] studio-tools throws json error
- [ ] studio-tools notifications not dark
- [ ] infinite-scrolling needs to check for the new style

**Comment by Samq64** [comment]
Copy comment link doesn't work. (At least on studios, I haven't checked on projects or profiles yet.)

**Comment by RedGuy12** [comment]
> Copy comment link doesn't work. (At least on studios, I haven't checked on projects or profiles yet.)

We can't repo that. Can you give your os info?

**Comment by Samq64** [comment]
> > Copy comment link doesn't work. (At least on studios, I haven't checked on projects or profiles yet.)
> 
> We can't repo that. Can you give your os info?

FireFox 89.02 on Windows 10 21H1

**Comment by apple502j** [comment]
Cannot repro on the same env.

**Comment by apple502j** [comment]
Does it work if you reload? Also are you sure you are using the addon? :P

**Comment by Samq64** [comment]
> Does it work if you reload? Also are you sure you are using the addon? :P

Yes, I reloaded and now it works.

**Comment by apple502j** [comment]
Probably one-time thing I guess.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
Bring back Change Name And Change Description And Change Thumbnail (if you are manager)

**Comment by apple502j** [comment]
No.

**Comment by Endermaster3690** [comment]
> Bring back Change Name And Change Description And Change Thumbnail (if you are manager)

ST wont like it

**Comment by pufferfish101007** [comment]
> > Bring back Change Name And Change Description And Change Thumbnail (if you are manager)
> 
> ST wont like it

More than that, it's completely impossible/if it is possible it's a big security vuln and shouldn't be abused.

**Comment by Hans5958** [comment]
> Bring back Change Name And Change Description And Change Thumbnail (if you are manager)

For transparency and the record, I need to point out to everybody and future readers that the reason that and some other suggestions can't be implemented because some, if not most of us didn't want to implement vulnerabilities, and probably ethical reasons. 

- "[We aren't Metasploit](https://discord.com/channels/806602307750985799/806602307750985803/863071571324174376)" and "[Implementing it means we're doing zero-day](https://discord.com/channels/806602307750985799/806602307750985803/863072000960757771)*," is what Apple said on regarding it being a vulnerability. 
- Ethical reasons is the same reason as why "invite all followers button" hasn't been implemented.

Except, we have "Higher character limit on "What I'm Working On"" The addon is implemented because this bug hasn't been fixed and it could be said as it is neglected for more than 90 days.

So, two things could happen.

1. This bug will be fixed in no later than 90 days and the suggestion won't be implemented forever.
2. The addon that utilize this bug will be made in no earlier than 90 days.
 
https://discord.com/channels/806602307750985799/806602307750985803/863075221132017716

* No, it wasn't. Seriously, no one told them?

**Comment by apple502j** [comment]
Note that there is no known way to change descriptions. It's not even 0day. It's negative day.

**Comment by RedGuy12** [comment]
Can this be closed now?
