### ISSUE TITLE
Prettier workflow doesn't work anymore

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#3098]
```sh
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>
```

**Comment by TheColaber** [comment]
Cannot repro, pls provide repro steps.

**Comment by Hans5958** [comment]
This is fine because the way it works.

- Try to format the code using Prettier.
- If there are changes, try to do a commit and push it.
  - If it succeeds, the code has been formated and the check succeeds.
  - If it isn't, the code hasn't been formatted and the check failed.
- If there aren't changes, the code has been formatted and the check succeeds.

So, basically, if the code formatted, it will succeeds, and if it isn't, it isn't.

When the workflow is allowed to run on the fork, the workflow runs on both the PR and the push event. Three things are happening when you push a commit while the code isn't formatted and the branch has it's PR open. The first two are happening in the same time.

- The check on PR fails because the workflow/check has failed to format the code. The workflow/check failed, and this is expected because it is the code hasn't been formatted.
- The check on the push event succeeds, but an additional commit is pushed. The workflow/chech has succeed to format the code. The workflow/check succeed, because the code has been formatted.
- Since another commit is pushed, the workflow/check on PR is run again. The check succeeds because the code has been formatted upon checking.

Based on that, the check works as it is and it behaves as expected, so yeah, this is not an issue.

**Comment by RedGuy12** [comment]
Wait so it's not supposed to format the code, just see if it is formatted? Because it no longer pushes any commits...

**Comment by wgyt** [comment]
I can reproduce this on my fork, it doesn't push the code and gives the error message:
> fatal: You are not currently on a branch.
> To push the history leading to the current (detached HEAD)
> state now, use
> ```
> git push origin HEAD:<name-of-remote-branch>
> ```
See https://github.com/ScratchAddons/ScratchAddons/pull/3097/checks

**Comment by TheColaber** [comment]
@wgyt im guessing you have not enabled actions in your repo?

**Comment by wgyt** [comment]
> @wgyt im guessing you have not enabled actions in your repo?

Oops, I thought it was 🤦🏻

**Comment by Hans5958** [comment]
> Wait so it's not supposed to format the code, just see if it is formatted? Because it no longer pushes any commits...

Read the first step. it supposed to format the code to check if it is formatted.

**Comment by RedGuy12** [comment]
So is it meant to push a commit formatting the code or not? Because it doesn’t

**Comment by Hans5958** [comment]
Dude, you seemed quick to respond even through e-mails. It's something that fasinates me. I turned off my Gmail notifs while you have it auto-sync.

Anyways, I have made an edit before you sending the message. Go to GitHub and read it.

**Comment by RedGuy12** [comment]
> Failed to push it? The code hasn't been formatted. Check failed.

it seems to me that it never gets pushed. Look at all the open prs. most of them have check failure due to prettier. the ones that don't must have linted manually.

**Comment by TheColaber** [comment]
@RedGuy12 Are you sure they have actions enabled? Also, only 3 or 4 prs have this problem.

**Comment by Hans5958** [comment]
> Also, only 3 or 4 prs have this problem.

All PR's behaves the same. The checks are checking if the code has been formatted, whether from the commit author or the workflow/check itself. It fails when (a) the code is not formatted and (b) the workflow can't fix the formatting by pushing commit.

**Comment by TheColaber** [comment]
@Hans5958 I meant about people who don't have actions enabled.

**Comment by Hans5958** [comment]
People with Actions enabled also have the same checks. The only difference is the PR check will go green eventually due to the workflow on their fork repo fixing it.
