### ISSUE TITLE
Scratch 2.0 → 3.0 addon breaks forum post links

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#3133]
### Description

Scratch 3.0 has a much larger UI than 2.0, and the Scratch 2.0 → 3.0 addon does not account for that - linking to forum posts cuts of some of the content.

### Repoduction steps

1. Go to a forum topic. 
2. Click the date on the first post.
3. Everything except the username should be visible
4. Click the date on the last post
5. A lot of the content should be cut off.
6. Turn off the Scratch 2.0 → 3.0 addon.
7. Repeat steps 2-4.
8. No content should be cut off.

### Expected behaviour

When linking to a forum post, all the content should be visible.

### Actual behaviour

When you link to the first post on the page, it hides the username, but everything else remains. But then try linking to the last post - a lot of the content is truncated. This does not happen with the Scratch 2.0 → 3.0 addon off.

### Environment

- Browser: Edge beta 92.0.902.55
- Scratch Addons version: 1.17.2
- Operating system: Windows 10 21H1 build 19043.1110

**Comment by RedGuy12** [comment]
Screenshot?



________________________________
From: Mr-Anonymous75 ***@***.***>
Sent: Tuesday, July 27, 2021 9:19:20 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Scratch 2.0 → 3.0 addon breaks forum post links (#3133)


Description

Scratch 3.0 has a much larger UI than 2.0, and the Scratch 2.0 → 3.0 addon does not account for that - linking to forum posts cuts of some of the content.

Repoduction steps

  1.  Go to a forum topic.
  2.  Click the date on the first post.
  3.  Everything except the username should be visible
  4.  Click the date on the last post
  5.  A lot of the content should be cut off.
  6.  Turn off the Scratch 2.0 → 3.0 addon.
  7.  Repeat steps 2-4.
  8.  No content should be cut off.

Expected behaviour

When linking to a forum post, all the content should be visible.

Actual behaviour

When you link to the first post on the page, it hides the username, but everything else remains. But then try linking to the last post - a lot of the content is truncated. This does not happen with the Scratch 2.0 → 3.0 addon off.

Environment

  *   Browser: Edge beta 92.0.902.55
  *   Scratch Addons version: 1.17.2
  *   Operating system: Windows 10 21H1 build 19043.1110

**Comment by WorldLanguages** [comment]
Yeah, screenshot/video please? And the example link you used for it?

**Comment by CodeGuy92** [comment]
Windows 10 Home (Ver 20H2) 19042.1110
Chrome 92.0.4515.107
ScratchAddons 1.17.2

I can't see this bug.
Do you mean that the navigation bar covers the post content? In that case, yeah, can replicate.
![image](https://user-images.githubusercontent.com/79767244/127444858-851a3034-a4a6-41d7-bce1-e4bc11ad0194.png)

**Comment by Mr-Anonymous75** [comment]
Hmm... Sometimes it happens, sometimes it doesn't...

**Comment by Mr-Anonymous75** [comment]
> Windows 10 Home (Ver 20H2) 19042.1110
> Chrome 92.0.4515.107
> ScratchAddons 1.17.2
> 
> I can't see this bug.
> Do you mean that the navigation bar covers the post content? In that case, yeah, can replicate.
> ![image](https://user-images.githubusercontent.com/79767244/127444858-851a3034-a4a6-41d7-bce1-e4bc11ad0194.png)
> 
> But, you can always just scroll up, mate.

Yep, thats what I mean. And yes, I know I can scroll up - but it'll be much more convenient to just have the link adjust for the larger UI in the first place.

**Comment by mxmou** [comment]
This happens without the addon, it's just less noticeable because you can see the whole first line of the post. Shouldn't be too hard to fix.
