### ISSUE TITLE
Re-add online player count for multiplayer games from Messaging Extension

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [ScratchAddons/ScratchAddons#339]
**Is your feature request related to a problem? Please describe.**

the cloud variable section in the old massaging extension has gone
did you forgot to add it back to the addon
**Describe the solution you'd like**

put that thing back
**Describe alternatives you've considered**

you can make it an optional setting by putting it in the setting menu
**Additional context**
put back these

<img width="362" alt="ภาพหน้าจอ 2563-09-27 เวลา 16 29 19" src="https://user-images.githubusercontent.com/66320961/94361461-a1aad800-00de-11eb-91ff-3ccda0329bd4.png">
<img width="357" alt="ภาพหน้าจอ 2563-09-27 เวลา 16 31 31" src="https://user-images.githubusercontent.com/66320961/94361522-0cf4aa00-00df-11eb-8e76-de9c6fd81454.png">

**Comment by Hans5958** [comment]
Hmm, it seems that we overlooked this exact feature, and turns out people actually use it. Someone from here will take a look with it, because I never used this.

cc @griffpatch @WorldLanguages

**Comment by JeffaloBob** [comment]
i heard they were talking about it.

if i understood it might include some kind of favourites row, so you can add more than griffpatch's games.

**Comment by griffpatch** [comment]
Yes - I originally populated it with my most popular multilayer games, but
i always intended that it might be customisable.
It always did show the player count and list the players for the 'current
project tab' and for all the popular games underneath.

I wanted to add a bookmark button next to the top 'current' game so you
could add it to the list (and then remove buttons for the other games would
be cool). I used these a lot to keep track of what was being played and be
able to jump into an active game. I know a lot of scratchers liked it
because it was like a little hub for people who wanted to find other
players.

**Comment by WorldLanguages** [comment]
@Hans5958, lol you ninja'd me into adding this into the v1.0.1 milestone

**Comment by griffpatch** [comment]
Awesome :)

One thing to consider is how we can add to the existing list when required
- Sure we can pre-populate with a list of projects, but once a user starts
to update their list, how do we manage when we want to add a 'new' project
to our default list when a new multiplayer game is released that is worth
including. Will we be able to auto add new ones to users lists even if they
have customised it themselves?

**Comment by WorldLanguages** [comment]
@griffpatch Hmm, we could split it into two lists: a curated list by us of popular multiplayer projects, which we can easily change with an update. As well as a list of projects selected by the user. If we split them up like that, it makes adding new projects to the list easier, since we don't have to deal with a single list which might (or might not) have been customized.

**Comment by JeffaloBob** [comment]
would the extension stores be ok with us getting the curated list of projects from a studio?

**Comment by WorldLanguages** [comment]
Huh nice idea. That would be perfectly fine.

**Comment by JeffaloBob** [comment]
> Huh nice idea. That would be perfectly fine.

ok cool
