### ISSUE TITLE
Easily toggle SA

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#3410]
# Motivation

Toggling SA is quite useful - maybe you want to know how your project will look without dark mode, or how it works without the debugger. Or maybe you want to know how your comment will look without line breaks inserted.
But, (at least in my browser) SA - or any other extension, for that matter - takes a lot of clicks to turn on or off. And what's worse, you have to refresh Scratch to disable most addons.

# Ideal solution

It would be really nice if there was a button, ideally in the title bar, to quickly toggle SA - without refreshing.

# Alternatives

You could just put a master switch in the settings page and the popup, which would temporarily disable all addons. Of course, this should take effect without refreshing.

**Comment by apple502j** [comment]
Scratch Addons sometimes adds its own stuff even if all addons are disabled. Also, disabling the extension or addons cannot remove certain elements which are overwriting vanilla Scratch behavior instead of adding or hiding (such as block shapes or comment linebreaks on profiles).

There are currently two ways:

1) Currently, Scratch Addons do not work on incognito, so you can open incognito windows. This will change in future versions.
2) Disable the whole extension and reload. You should bookmark the browser's settings page.
