### ISSUE TITLE
Chrome: use declarativeNetRequestWithHostAccess instead of webRequestBlocking

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#3615]
EDIT: outdated

The new `declarativeNetRequestWithHostAccess` permission will ship in Chrome stable on November 16 2021.
Around three months later (February 2022), we'll remove the `webRequestBlocking` permission from our Chrome manifest.json and start using `declarativeNetRequestWithHostAccess` instead.
Users running Chrome 95 and below will still be able to use Scratch Addons by then, except some scratch-messaging and scratch-notifier features (more detail below).
Firefox will continue to use `webRequestBlocking`, possibly forever.

We currently use blocking webRequest for:
- Fetching `?sareferer` URLs (used to delete/post comments and clear message count from background/popup contexts)
- ~~Removing `Set-Cookie` headers from `https://scratch.mit.edu/site-api/comments/*` responses which unexpectedly log users out.~~ **Removed in v1.24.3 through #4237 and no bug reports received about unexpected logouts yet.**

Moving away from webRequestBlocking is a good first step to be ready for manifest v3, and may also possibly speed up our Chrome Web Store review times.

**Comment by WorldLanguages** [comment]
> (added by quoter: this probably means that profile comments won't work)

No, they'll still work. All we did to those URLs is prevent them from logging the user out.
URL param `sareferer` is used for:
- Marking messages as read (scratch messaging and notifier)
- Posting comments, deleting comments, clearing alerts (scratch messaging)

**Comment by RedGuy12** [comment]
Maybe we can change webRequestBlocking to an optional permission and only request it if declarativeNetRequestWithHostAccess isn't supported


________________________________
From: World_Languages ***@***.***>
Sent: Wednesday, October 6, 2021 5:53:23 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Chrome: use declarativeNetRequestWithHostAccess instead of webRequestBlocking (#3615)


The new declarativeNetRequestWithHostAccess permission will ship in Chrome stable on November 16 2021.
Around three months later (February 2022), we'll remove the webRequestBlocking permission from our Chrome manifest.json and start using declarativeNetRequestWithHostAccess instead.
Users running Chrome 95 and below will still be able to use Scratch Addons by then, except some scratch-messaging and scratch-notifier features (more detail below).
Firefox will continue to use webRequestBlocking, possibly forever.

We currently use blocking webRequest for:

  *   Fetching ?sareferer URLs (used to delete/post comments and clear message count from background/popup contexts)
  *   Removing Set-Cookie headers from https://scratch.mit.edu/site-api/comments/* responses which unexpectedly log users out.

Moving away from webRequestBlocking is a good first step to be ready for manifest v3, and may also possibly speed up our Chrome Web Store review times.

**Comment by WorldLanguages** [comment]
webRequestBlocking does not have any "permission warnings" so there's no real difference in the review process between making it required or optional.

**Comment by WorldLanguages** [comment]
Since v1.38.0 we no longer request the `webRequestBlocking` permission in Chrome (as it's impossible to do so with manifest v3)

We still use WBR for Firefox < 113 though (see handle-fetch.js)

**Comment by YeahhhhBoy** [comment]
http://127.0.0.1
