### ISSUE TITLE
Savable Runtime State

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3712]
So, a way to save the entire state of the Scratch runtime, which could then be loaded later, effectively adding a save mode to *every* game? (So like persistent save states in lots of video game emulators.)

I think that would be best as a distinct addon from this (so a new issue), and while it's not something Scratch native can do, neither is pausing the project altogether; I think this would be a really cool addon to see distinct from list/ask-prompt loading!

_Originally posted by @towerofnix in https://github.com/ScratchAddons/ScratchAddons/issues/1990#issuecomment-811057718_
____
I know this is overly complicated for an addon, but I thought I would make a separate issue for it anyway.

**Comment by ninjamar** [comment]
This would be cool

**Comment by FunctionalMetatable** [comment]
This probably wont work as well as project authors could update the project which could affect where we have to resume code execution

**Comment by Samq64** [comment]
I didn't think of that.

**Comment by BroJac5246** [comment]
> This probably wont work as well as project authors could update the project which could affect where we have to resume code execution

Could the project file be downloaded as well, and zipped with the file containing the project's state? A lot of Scratch projects aren't that large, although this could still be problematic for larger files.

Or, if that's not acceptable, could the hash of the project be saved with the state file, so that when the state is loaded, the user will be warned if the hashes of the two projects don't match?

**Comment by CST1229** [comment]
> Could the project file be downloaded as well, and zipped with the file containing the project's state? A lot of Scratch projects aren't that large, although this could still be problematic for larger files.
> 
> Or, if that's not acceptable, could the hash of the project be saved with the state file, so that when the state is loaded, the user will be warned if the hashes of the two projects don't match?

Or just the project.json, which can usually only be ~5MB max in a project (and the other assets can just be downloaded).

**Comment by towerofnix** [comment]
> Or, if that's not acceptable, could the hash of the project be saved with the state file, so that when the state is loaded, the user will be warned if the hashes of the two projects don't match?

Even with just project.json, I think the 5MB per project (or potentially per unique-revision-with-save-states) would add up pretty quickly—so I like this idea better, hashing the project.json and indicating if there have been changes.

Admittedly, most projects don't come that close to the 5MB limit, and there are probably way better dedicated, community-made compression formats for sb3 project.json files out there—which could cut down even a big project into a much smaller binary format. (Or if it doesn't exist, someone could make one. :P)

I'm not sure how much storage space is allotted to extensions, so it could still be an eventual concern, but there *is* potential.

Playing on an unshared remix of a project (thus frozen in its current state, unmodified as long as you don't make edits yourself) is always a viable solution, too.

Side note that hasn't been mentioned on this issue: Restoring from a saved runtime state should disable connection to the cloud variable servers. We don't want people cheating - or worse, outright breaking (due to unexpected interactions) - multiplayer games and other cloud projects! (Restoring from the save state itself is probably fine, but indicate - when saving - that cloud features will be disabled when you load the save state.)

**Comment by BroJac5246** [comment]
> Even with just project.json, I think the 5MB per project (or potentially per unique-revision-with-save-states) would add up pretty quickly—so I like this idea better, hashing the project.json and indicating if there have been changes.

I was thinking that the state would be downloaded, but it's certainly possible to keep it in the browser. I'm thinking the addon could have a limit on the number of states that can be saved at once. If you want more, you'd have to download them to the computer's storage. We should definitely look into hashing, but my concern is that even a small, unnecessary change could cause a difference in the hashes (which we would obviously want to avoid). For that reason, we might want to look into creating a custom version of the project.json only for hashing. Still, both options have potential.

> Side note that hasn't been mentioned on this issue: Restoring from a saved runtime state should disable connection to the cloud variable servers. We don't want people cheating - or worse, outright breaking (due to unexpected interactions) - multiplayer games and other cloud projects! (Restoring from the save state itself is probably fine, but indicate - when saving - that cloud features will be disabled when you load the save state.)

Good point. I fully agree.

**Comment by Secret-chest** [comment]
Why are you closing?

**Comment by Secret-chest** [comment]
>  features will be disabled when you load the save state.

We can add a magic project comment to enable cloud variables after loading a save.

**Comment by Samq64** [comment]
> Why are you closing?

It's a cool idea in theory but would probably very buggy and could cause project corruption if the project creator opens the editor and it auto-saves. I might be wrong though.

**Comment by WorldLanguages** [comment]
Serializing the state of the Scratch runtime into a file and being able to restore it later sounds like quite a challenge.
The idea is good but you could close this for being close to impossible.

It sounds more reasonable to think there should exist a tool where the entire state of a browser tab can be downloaded and retrieved - DOM, events, all JS memory, etc.
It would be quite useful for lots of applications, not just Scratch.
