### ISSUE TITLE
Notice: All PRs open at 02:33 GMT have been accidentally closed

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#372]
All PRs have been accidentally closed. You can re-pr now. @Hans5958 accidentally force-pushed, and that caused all open PRs at the time to be closed. We are sorry for the inconvenience.

**Comment by Hans5958** [comment]
At Friday, 2 October 2020, 02:33:59 GMT, I accidentally force-pushed a new repository into the this repository. This caused the repository had it's history replaced. Thankfully, all commits, except a single merge commit, have been recovered. The mentioned merge commit have also been replaced. 

However, all pull request that is open on the mentioned time have been forcefully closed, so those pull requests must be re-requested. The affected pull request are as follows:
- #209 Line breaks in comments 
- #312 Add my forum editor addon
- #335 Add editor-stage-left addon
- #360 Added link to the chrome webstore
- #370 Make signature expand button cleaner

I also have left a comment on all mentioned pull request.

I apologize for the inconvenience that is caused by my mistake. I will try to be more careful in the future.

**Comment by Explosion-Scratch** [comment]
I think now all the owners of those PR's have either resubmitted the PR, responded that it didn't matter or both. I'll unpin this now.
