### ISSUE TITLE
"mediarecorder" should use mp4 instead of webm

### ISSUE THREAD

**Issue by CubeyTheCube** [ScratchAddons/ScratchAddons#3818]
### Description
Currently when you record the stage using the mediarecorder addon, it's exported as a webm file. webm may be designed for the web and all, but the video quality is not great. Also, the length of webm videos does not seem to be predetermined, making them do things like this when you view them:
![image](https://user-images.githubusercontent.com/72284516/142080937-68289144-f408-4a35-b183-123a8f1beca7.png)
mp4 is generally a better format, which is why I think the video recorder addon should use it.

**Comment by RedGuy12** [comment]
Would be extremely complicated


________________________________
From: CubeyTheCube ***@***.***>
Sent: Tuesday, November 16, 2021 5:13:40 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] "mediarecorder" should use mp4 instead of webm (Issue #3818)


Description

Currently when you record the stage using the mediarecorder addon, it's exported as a webm file. webm may be designed for the web and all, but the video quality is not great. Also, the length of webm videos does not seem to be predetermined, making them do things like this when you view them:
[image]<https://user-images.githubusercontent.com/72284516/142080937-68289144-f408-4a35-b183-123a8f1beca7.png>
mp4 is generally a better format, which is why I think the video recorder addon should use it.

**Comment by WorldLanguages** [comment]
If it was simple, we would have gone with mp4 or let the user choose. But MediaRecorder API only supports webm universally in all browsers.
