### ISSUE TITLE
Dark mode is broken when becoming scratcher

### ISSUE THREAD

**Issue by PoIygon** [ScratchAddons/ScratchAddons#3829]
### Description
When i was becoming a scratcher on my other account that Im not telling you about i saw that the css was broken

### Repoduction steps

1.  create an account
2.  turn on the dark mode addon
3.  become a scratcher

### Expected behaviour

The text boxes should be filled with white and the boxes at the bottom should be white too
### Actual behaviour

the textboxes and boxes aren't white

### Screenshots
![image](https://user-images.githubusercontent.com/79771454/142718946-3c8b71d3-d295-4d52-aa59-93c6b18461b9.png)
![image](https://user-images.githubusercontent.com/79771454/142718972-2791a15a-5a2a-4690-9d3d-37a91d99891e.png)
![image](https://user-images.githubusercontent.com/79771454/142718976-60c5fc05-5672-4e9a-8af2-8e5f8824f8c0.png)
![image](https://user-images.githubusercontent.com/79771454/142718994-d699aedb-d26f-4487-b970-b6c6a4ac6679.png)
![image](https://user-images.githubusercontent.com/79771454/142719002-c3748ab4-76a5-4939-8eba-a37aab685142.png)
![image](https://user-images.githubusercontent.com/79771454/142719019-1dc56208-2b6c-47fe-8fa8-fbad0b9c2956.png)

### Environment

- Browser:  Firefox 94
- Scratch Addons version:  1.22.1
- Operating system:  Windows 10

**Comment by RedGuy12** [comment]
Odd, because #2167 fixed this in v1.13.0...


________________________________
From: Polygon ***@***.***>
Sent: Friday, November 19, 2021 11:58:23 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Dark mode is broken when becoming scratcher (Issue #3829)


Description

When i was becoming a scratcher on my other account that Im not telling you about i saw that the css was broken

Repoduction steps

  1.  create an account
  2.  turn on the dark mode addon
  3.  become a scratcher

Expected behaviour

The text boxes should be filled with white and the boxes at the bottom should be white too

Actual behaviour

the textboxes and boxes aren't white

Screenshots

[image]<https://user-images.githubusercontent.com/79771454/142718946-3c8b71d3-d295-4d52-aa59-93c6b18461b9.png>
[image]<https://user-images.githubusercontent.com/79771454/142718972-2791a15a-5a2a-4690-9d3d-37a91d99891e.png>
[image]<https://user-images.githubusercontent.com/79771454/142718976-60c5fc05-5672-4e9a-8af2-8e5f8824f8c0.png>
[image]<https://user-images.githubusercontent.com/79771454/142718994-d699aedb-d26f-4487-b970-b6c6a4ac6679.png>
[image]<https://user-images.githubusercontent.com/79771454/142719002-c3748ab4-76a5-4939-8eba-a37aab685142.png>
[image]<https://user-images.githubusercontent.com/79771454/142719019-1dc56208-2b6c-47fe-8fa8-fbad0b9c2956.png>

Environment

  *   Browser: Firefox 94
  *   Scratch Addons version: 1.22.1
  *   Operating system: Windows 10

**Comment by mxmou** [comment]
> Odd, because #2167 fixed this in v1.13.0...

#3577 broke it again - it made the modal background dark, but the code added in #2167 that made the text black was not removed.
