### ISSUE TITLE
'Editor dark mode and customizable colors' have bug color website editor

### ISSUE THREAD

**Issue by LynPhamEXE** [ScratchAddons/ScratchAddons#3856]
I don't know how to explain this bug but I will call that

'Editor dark mode and customizable colors' bug color. When I try to use Scratch's default colors, it turn to be this. I have try to delete Scratch addons and download it back but they still have that bug. I think the problem is the color they change the color effect but I don't know how to fix it

### Repoduction steps

1.  turn on 'Editor dark mode and customizable colors'
2. Set color to TurboWarp Dark
3.  Turn on 'Customizable block colors'
4. Set TEXT COLOR to colored on black background
5. Set preset to dark
6. One day it hapens 

### Expected behaviour

Fix color effetc.

### Actual behaviour

 The color effect doesn't change after reset it back

### Screenshots

![moa](https://user-images.githubusercontent.com/95167118/143767348-8f99fa94-1226-43b9-abeb-b38c35db1342.PNG)
### Environment

- Browser:  Chrome 
- Scratch Addons version:  1.22.1
- Operating system: Windows 7

### Additional context

(https://user-images.githubusercontent.com/95167118/143767362-409d8371-db5a-4f4d-8517-b77a93b82d26.PNG)

**Comment by Samq64** [comment]
Reload the page. Addons can't dynamically disable properly when the whole extension is disabled or removed.

**Comment by RedGuy12** [comment]
Do you have any other extensions installed?


________________________________
From: LynPhamEXE ***@***.***>
Sent: Sunday, November 28, 2021 6:17:51 AM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] 'Editor dark mode and customizable colors' have bug color website editor (Issue #3856)


I don't know how to explain this bug but I will call that

'Editor dark mode and customizable colors' bug color. When I try to use Scratch's default colors, it turn to be this. I have try to delete Scratch addons and download it back but they still have that bug. I think the problem is the color they change the color effect but I don't know how to fix it

Description
Repoduction steps

  1.  turn on 'Editor dark mode and customizable colors'
  2.  Set color to TurboWarp Dark
  3.  Turn on 'Customizable block colors'
  4.  Set TEXT COLOR to colored on black background
  5.  Set preset to dark
  6.  One day it hapens

Expected behaviour

Fix color effetc.

Actual behaviour

The color effect doesn't change after reset it back

Screenshots

[moa]<https://user-images.githubusercontent.com/95167118/143767348-8f99fa94-1226-43b9-abeb-b38c35db1342.PNG>

Environment

  *   Browser: Chrome
  *   Scratch Addons version: 1.22.1
  *   Operating system: Windows 7

Additional context

(https://user-images.githubusercontent.com/95167118/143767362-409d8371-db5a-4f4d-8517-b77a93b82d26.PNG)

**Comment by WorldLanguages** [comment]
Yeah, @LynPhamEXE do you use any other extensions that have access to scratch.mit.edu?

**Comment by LynPhamEXE** [comment]
I using Chrome 96

**Comment by LynPhamEXE** [comment]
> Yeah, @LynPhamEXE do you use any other extensions that have access to scratch.mit.edu?

No, I don't use any other extension

**Comment by RedGuy12** [comment]
@LynPhamEXE Even just two copies of SA can mess it up


________________________________

**Comment by RedGuy12** [comment]
Closing as stale.
