### ISSUE TITLE
hi-res-thumbnails should scale images based on container size

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3893]
### Is your request related to a problem? Please describe.

If I enable `hi-res-thumbnails` and set the scaling to 100% I would expect all images across the site to be the same size as the container they're displayed in, but images that are displayed at high resolutions by default are untouched.

### Describe the solution you'd like

Make `hi-res-thumbnails` scale images based on container sizes instead of image sizes.

### Describe alternatives you've considered

Make it togglable.

**Comment by WorldLanguages** [comment]
@towerofnix

**Comment by towerofnix** [comment]
See [this point of discussion](https://github.com/ScratchAddons/ScratchAddons/pull/3769#discussion_r745289783), which I brought up but apparently everyone (including me) forgot to talk through before merging :P

> One point of discussion re: implementation of this resolution fix: maybe it makes sense to *down*scale images which are by default loaded in at a higher resolution than they're actually displayed at? (Before applying the user-specified multiplier, of course.)
>
> The main example I found of this is on the new studio pages, where for some reason thumbnails are loaded at 480x360, even though they're displayed at only about 217x203 in CSS pixels on a 1920p screen. This addon would actually save a little data usage if you set the res setting to 100% and had this fix enabled, then, because it would fetch the images at 217x203 instead of 480x360!
>
> Although apparently, studio thumbnails load a higher res because the rendered size is semi-flexible, i.e. at thinner displays (e.g. by shrinking the window) it'll only show two projects per row, and this can get the thumbnails to around 345x260 CSS pixels. Still less than 480x360, though not by as much. Just the same, it points out a flaw with downscaling to the rendered size: if the image later dynamically *expands,* it'll look lower resolution than the original developers were giving excess dimensions as a way of intentionally allowing for!

The latter point is the main concern with implementing this (which IIRC would be about as simple as removing the `if (scale > 1)` check).

Major options forward:

1. Special-case images whose containers might later expand, like on studio pages (which might be the only ones, but other dynamic/scratch-www pages could have more). Either skip downscaling these altogether or decide on some maximum realistic/theoretical size (i.e. in CSS pixels).
2. Don't bother caring about dynamic containers at all, always using the dimensions that are present when the userscript runs. Justification: changing the size of the window is analogous to changing the zoom scale, which we don't try to detect. However, the reason for *that* is because there are [a host of other problems with dynamic scaling](https://github.com/ScratchAddons/ScratchAddons/pull/3769#discussion_r745292380), particularly dynamically loading *new* images as the page zooms.
3. Dynamically detect containers changing sizes and calculate new dimensions as a result—definitely not an option, see above :P
4. ???
5. Profit

Possible concerns / additional context:

* Make sure containers don't have smaller dimensions *before the image is loaded*. I.e, if a container is 200px by 0px before its content image has loaded, we don't want to scale down to that zero height dimension!
* Make sure we're operating before images initially load, in the first place—downscaling is pointless if it only happens after the higher resolution has loaded.
* We should deliberately replace images loaded from projects.scratch.mit.edu with corresponding cdn2 URLs, with the appropriate dimensions. Otherwise, we aren't saving nearly as much network data as we could be!

**Comment by Samq64** [comment]
Right... I guess this isn't such a good idea then.

**Comment by towerofnix** [comment]
No, it's still a good idea and has a lot of reason to implement! Scratch definitely wastes a sizeable amount of data on images, and in an addon which is all about scaling images to the user's desired resolution, it's a perfect fit to fix that issue.

There are very few image containers that dynamically resize. Only two page types could reasonably have *any* (studio pages and project pages), and those aren't difficult to special case once we're sure which containers change sizes. Compare to the homepage, where there are tons of project thumbnails loaded at 480x360 that *never* resize—those we can scale down to an appropriate ~145x110 for free!
