### ISSUE TITLE
Bugs on "data category tweaks"

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#396]
> Sometimes, a list got duplicated with the same name, and the exact same content. When i deletes the real list, the "ghost list" still exist, but the list section is empty.. I reloaded but its still the same. The next day, I found out that the ghost list suddenly changed from a global list to a local list, plus its now showing in the for this sprite only list section... 

> Sorting "this sprite only" variables is broken. 

> The separation for lists and local variables do not work properly after programming.

> For the variables and list ( for this sprite and all sprite ), sometimes it works, sometimes it shows the previous version and the separated version, so basically 2 variables group.

**Comment by Explosion-Scratch** [comment]
@towerofnix ^^^

**Comment by RokCoder** [comment]
I'm encountering this issue frequently. I haven't noticed the list reappearing as local though. This is particularly gnarly as I tend to notice it when a list is being displayed. When the bug occurs there's no way to hide the list (other than to manually attack the json) but a duplicate list can be toggled on and off.

**Comment by mxmou** [comment]
I've actually seen posts in Scratch's Bugs and Glitches forum about this, so I think it's a serious problem.

https://scratch.mit.edu/discuss/topic/444244/
https://scratch.mit.edu/discuss/topic/445060/

**Comment by WorldLanguages** [comment]
Oh wow, this got into the Bugs and Glitches forum

**Comment by towerofnix** [comment]
Just putting some notes here so they're public (and in case I can't figure out where to go from here) - I'm working on this ATM:

> Sometimes, a list got duplicated with the same name, and the exact same content. When i deletes the real list, the "ghost list" still exist, but the list section is empty.. I reloaded but its still the same. The next day, I found out that the ghost list suddenly changed from a global list to a local list, plus its now showing in the for this sprite only list section...

(Terminology note: list "monitors" and "variables" are different. A **list variable** is the internally stored VM/Blockly object which contains the items in the list, its name, ID, etc. A **list monitor** is the on-screen display for that list. It references a list variable by name (not ID), and there is normally exactly one monitor for every list variable.)

@WorldLanguages and I found a few things while investigating [this project](https://scratch.mit.edu/projects/432567841/editor/) (which includes a few cases of the bug):

**On list behavior:**

1. The "ghost list" is actually a duplicate list monitor. It references the same list as the original monitor. When attempting to interact with the monitors for a list variable (e.g. with the toggle next to the list block in the palette), Scratch will always target the original monitor, since it only expects there to be one monitor extant per list variable. As such:
2. The checkbox reflects the original monitor. If you click it, you'll only hide or show the original monitor. The duplicate ("ghost") monitor cannot be hidden (there is no way to interact with it to hide it).
3. Deleting the list variable altogether will delete the original monitor, but not the ghost monitor. (The contents of the ghost monitor are still emptied though, hence `When i deletes the real list, the "ghost list" still exist, but the list section is empty`.)
4. Refreshing the block palette will reveal the list variable is restored. I believe this is because it is still referenced by the remaining ghost monitor (Scratch [automatically creates](https://github.com/LLK/scratch-vm/blob/7eabcb8a2965f7f02b7881da720d29cde8b70150/src/engine/target.js#L251-L253) a new local monitor when a list is referenced but doesn't yet exist, or has been deleted). This is also the reason behind `The next day, I found out that the ghost list suddenly changed from a global list to a local list, plus its now showing in the for this sprite only list section...`.
5. (Side-note: a ghost list can be permanently deleted & removed from the editor by deleting it *thrice* (delete, switch to other sprite, switch back to original sprite, repeat). I don't really know why this is, but it doesn't appear again after the third time. I think it has to do with only removing the final monitor ref after the third time, but I'm not sure. Probably not relevant to fixing this bug though.)

**On project data:** *(See [project_truncated.json](https://gist.github.com/towerofnix/575a331db5a3a11f46520f0df0631c41) for a truncated version of the project.json, with only 10 items per list. The actual project.json contains several thousand items in each list.)*

6. As mentioned, we're dealing with a duplicate list *monitor*. There is no actual new list, see `targets[0].lists`. (We noticed that, at least for "Red X", the (typically redundant) `value` saved in the duplicate monitor is not the same as in the original monitor, but this is a red herring and probably just a side effect of the way monitors are saved. The two monitors still reference the same list variable (`{params: {LIST: "Red X"}}`) and accordingly reflect changes to that list identically, when shown.)
7. There's a duplicate monitor for every list, not just one.
8. The duplicate monitors are all visible. **The monitors which are newly created alongside a referenced monitor are *not* made visible by default, so I don't think that's how the duplicate monitors are coming about.**
9. I'm not sure how else the duplicate monitors are originally being created though.

Figuring out that last mystery point is how we can fix this problem. (With knowledge of where the duplicate monitors are coming from, we could move on to figure out a fix.)

I'm *guessing* it has to do with the way that the list palette is cached and then recreated, but am not sure. I don't yet have a solid repro case for creating "ghost lists" as the original quote describes them - hence why I've been working with this existing project. Finding a reliable repro case would make probably debugging the problem considerably easier.

**Comment by WorldLanguages** [comment]
More feedback:

> The data category tweaks is glitching... and now after I made a list, it just disappears.... and the entire list section too...

Sadly it looks like this addon has too many side effects that are difficult to reproduce

**Comment by WorldLanguages** [comment]
I'll be removing this addon from the next release, even if a solution is found. Sadly this is still frequently happening to users and it keeps appearing in the bugs and glitches forum. If we do find a solution let's first test it ourselves for a while, then release as beta, then wait some time to mark it as stable.

**Comment by GrahamSH-LLK** [comment]
This addon has been gone for 20 days. I'm closing this issue.
