### ISSUE TITLE
Messages Lagging

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#3971]
### Description

It says 3 (and displays 3) but I have 5

### Repoduction steps

1. Get a few messages quickly
2. Check messages
3. wait a few minutes and it will show

### Expected behaviour

Displayes it correctly

### Actual behaviour

it laaaaaaaaaaaaaaaaaaaaaags

### Environment

Firefox

**Comment by RedGuy12** [comment]
Does https://api.scratch.mit.edu/users/your-username-here/messages/count display the proper number? If so, not our problem.


________________________________
From: Mbrick2 ***@***.***>
Sent: Monday, December 20, 2021 8:04:47 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Messages Lagging (Issue #3971)


Description

It says 3 (and displays 3) but I have 5

Repoduction steps

  1.  Get a few messages quickly
  2.  Check messages
  3.  wait a few minutes and it will show

Expected behaviour

Displayes it correctly

Actual behaviour

it laaaaaaaaaaaaaaaaaaaaaags

Environment

Firefox

**Comment by apple502j** [comment]
Duplicate of #2872
