### ISSUE TITLE
`hi-res-thumbnails` breaks some images

### ISSUE THREAD

**Issue by just-a-hriday** [ScratchAddons/ScratchAddons#3987]
## Description

Some images on the forums, specifically my PFP inside my siggy, get scaled instead of increasing in resolution.

### Repoduction steps

1. Look at one of my posts, like [my portfolio](https://scratch.mit.edu/discuss/topic/541995/).
2. Scroll down to my siggy, and look at my PFP.

### Expected behaviour

My PFP should just increase in resolution.

### Actual behaviour

My PFP in my siggy, which uses `cdn2.scratch.mit.edu`, gets scaled up instead of increasing in resolution. The image URL for it is `https://uploads.scratch.mit.edu/get_image/user/{user-id}_90x90.png`.

### Screenshots

![high-res-thumbails bug](https://user-images.githubusercontent.com/73294041/147257071-8d517cb9-d141-48a0-a18d-8983019fbabe.png)

### Environment

- Browser: Microsoft Edge 97.0.1072.41 Beta and Firefox Developer Edition 96.0b8
- Scratch Addons version: v1.23.2
- Operating system: Windows 11

**Comment by RedGuy12** [comment]
cc @towerofnix

**Comment by towerofnix** [comment]
Oh huh.

So, the trouble with these is that they don't have anything specifically setting them to an appropriate width/height—product of user-embedded images (Scratch has no way of guessing the dimensions so it doesn't set `width`/`height` HTML attributes or CSS properties).

What I don't understand is why these are successfully scaling up instead of displaying at 0x0, since theoretically that's what the code should be doing—looking at a bounding box for an unloaded image which takes up no space, downscaling to 0x0, then upscaling to `<config multiplier> * 0x0 = 0x0`.

Anyway, I think the correct solution here is one of two things:

* *Figure out* why `getBoundingClientRect` works on user-embedded images on forums, then set `width` / `height` attributes ourselves after increasing the resolution. (This feels a little dangerous, but it would have the intended affect of increasing resolution.)
* Ignore images embedded on the forums, since we don't have super great control/prediction over how those render, unlike images elsewhere on the site. (This is less risky but not 100% true—forum images are always plain `<img src>`, no width/height HTML or CSS, so we might be able to find a solution which works for them.)

The latter can be done as a hotfix before the former (which can be done later if anyone has interest in further investigating). I won't personally have time to work on fixes over Christmas and my work week after, sorry!
