### ISSUE TITLE
`forum-id` should use post IDs and not topic post numbers (or whatever they're callled)

### ISSUE THREAD

**Issue by Dhuls-Scratch** [ScratchAddons/ScratchAddons#4048]
Post numbers can change (for example: when posts get deleted, or when topics get merged), but post IDs don't (to my knowledge). You can also simply type `scratch.mit.edu/discuss/post/123456` to find that post but it's highly unlikely to do that with the post numbers.

**Comment by RedGuy12** [comment]
The current behavior is widely used in the Japanese (? Maybe a different one icr)  forum so that's what the original addon creator did

Not saying I agree with that behavior but just giving the reasoning


________________________________
From: Dhuls-Scratch ***@***.***>
Sent: Monday, January 10, 2022 6:19:44 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] `forum-id` should use post IDs and not topic post numbers (or whatever they're callled) (Issue #4048)


Post numbers can change (for example: when posts get deleted, or when topics get merged), but post IDs don't (to my knowledge). You can also simply type scratch.mit.edu/discuss/post/123456 to find that post but it's highly unlikely to do that with the post numbers.

**Comment by apple502j** [comment]
Keeping current behavior for now.
