### ISSUE TITLE
Laggy Debbuger

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4180]
https://user-images.githubusercontent.com/90691415/152486591-0afb5464-e29d-45b3-9ca3-292589947f37.mov

**Comment by Chiroyce1** [comment]
Can you provide some more info?

**Comment by Norbiros** [comment]
After testing this with different tools (mozzila web browser performace, computer performace etc.) - problem is not with Debbuger itself. It works verry fine. Real problem is with showing data - it makes lag. _To test it - open debbuger, go to other tab, and after 3 minutes go back - it will be normal_.

**Comment by WorldLanguages** [comment]
@Mbrick2 Could you explain?

**Comment by Norbiros** [comment]
There are 2 properties that are lagging: `fill` and `animation`. Disabling fill looks bad for me, but IDK... These are data with specific properties on the same code:

Animation disabled, but fill allowed:
![Screenshot from 2022-02-04 18-50-59](https://user-images.githubusercontent.com/89837724/152578100-f0fb7fa5-52cc-4688-bd47-b506dcb4aedf.png)

Animation disabled, fill disabled:
![Screenshot from 2022-02-04 18-48-06](https://user-images.githubusercontent.com/89837724/152578307-4d78c927-0f8e-49a9-ad06-7767d6ce7d44.png)

Default settings:
![Screenshot from 2022-02-04 18-47-20](https://user-images.githubusercontent.com/89837724/152578329-e927e5a9-64b7-4f22-836f-5156a1bffc3f.png)

**I have big values, because i have good internet and computer, maybe MrBrick have worse... But it will help him more than me**

I think we can add setting `Optimized: true/false`. I just love looking at this graphs <3!

**Comment by Mbrick2** [comment]
> @Mbrick2 Could you explain?

The fps dropped when I opened the debugger

**Comment by Chiroyce1** [comment]
> The fps dropped when I opened the debugger

Can sort of replicate, average FPS went from `27.8` to `25.6` when I opened the debugger in the first try, and `27.8` to `25.4` in the second try.

https://user-images.githubusercontent.com/97374054/152642982-d13d4d85-5866-4c91-bd74-2f9c6470c339.mov

**Comment by RedLight-Scratch** [comment]
> With Firefox's DevTools, I got `58.63` FPS without the debugger open and `57.98` FPS with it open, which is a very minor difference. But this does remove around `2 FPS` on the Scratch project.

With Firefox for me, the fps drops from 30 to 20 (No turbo mode or 60 fps). It is a pretty big change.

**Comment by Norbiros** [comment]
This depends, how your computer is good, how your browser is modern, and how good graphic card you have...
