### ISSUE TITLE
Automatic Machine Translation Add-on

### ISSUE THREAD

**Issue by ilbailba** [ScratchAddons/ScratchAddons#4290]
### Is your request related to a problem? Please describe.

The problem is: some projects are not made in the _native languages_ of the users. And so places like "**Instructions**" and "**Notes and Credits**" can be in _different languages_. I'm not just saying this for **English**. I mean **Notes and credits** could be written in **all languages**
_(Or there may have been a typo)_.

![Eng](https://user-images.githubusercontent.com/71350431/154815397-a71c4001-107b-4abb-97bd-87b2f14ae61a.png)
![Tur](https://user-images.githubusercontent.com/71350431/154815398-c1713a16-152d-461d-a0ef-b7fca8949ab4.png)

### Describe the solution you'd like

That's why a plugin can be made that makes **machine translations** for them _automatically_. This plugin can also use a **machine translation** already done, or it can also use a _machine translation_ by **SA**. I think this is much more customizable than **Google's Translate program**. In addition, **Google Translate** translates the whole page and this is a much more difficult process. And this can be done not just for "**Notes and Credits**" or "**Instructions**", but for comments or any unique writing you can think of.

### Describe alternatives you've considered

**auto translate** => _if there is a text in the main language on the page, it will translate it._
|-> **translate comments**
|-> **Translate "Instructions**" and "Notes and Credits"
|-> **Translate project names** _**(not recommended)**_
.
.
.
etc... _(Settings such as About me, What I'm working on, Profile comments can also be added)_

**Use []'s machine translation system**
|-> **Use Scratch Addons' translation system**
|-> **Use Google Translate's translation system**
.
.
.
etc...

### Additional context

_I checked if there is a thread similar to this one, but there were too many posts under the name "translate". but I couldn't find a thread about "auto". That's why I opened this issue. I can also guess that the probability of this happening is very low. I just wanted to express my opinion._

**Thanks.**

**Comment by CST1229** [comment]
> or it can also use a _machine translation_ by **SA**

How would SA machine translate the notes/instructions?

**Comment by ilbailba** [comment]
> > or it can also use a _machine translation_ by **SA**
> 
> How would SA machine translate the notes/instructions?

I meant to say "A Machine Translation program can be made for this plugin". But just a suggestion as I know this is difficult. Google Translate is enough for that.

**Comment by Norbiros** [comment]
From technical side  the biggest problem is:
Permission for accessing sites. Scratch Addons only have permission for Scratch pages. I think we don't want to add new pages due to: 558...

Also in these times almost 64% of users use Chrome, that have function like this.

IMAO, thanks for great issue (almost no one sends that big issues 👍🏻 ), but **I** think it is unnecessary, but as always, last word to @WorldLanguages

**Comment by CST1229** [comment]
> Permission for accessing sites. Scratch Addons only have permission for Scratch pages. I think we don't want to add new pages due to: 558...

SA already makes requests to ScratchDB and ocular, an extension doesn't need host permissions for a domain to fetch from that domain.

**Comment by RedGuy12** [comment]
Google translate free api does have (per-device) limits that we would probably exceed.

> In these times almost 64% of users use Chrome, that have function like this.

Chromium has this built in and other extensions work for Firefox. Other browsers don't matter since the addon wouldn't work on thwm anyway.

> but as always, last word is to WorldLanguages `It is only mine opinion....`

No need to ping him...




This would be rejected anyway since the addon wouldn't have any scratch-specific code.

**Comment by WorldLanguages** [comment]
I don't think it makes sense to be in charge of the automatic translation ourselves.

However, considering this:
> Google Translate translates the whole page and this is a much more difficult process.

There could be an addon that adds the `notranslate` attribute to parts of the page as the user chooses (e.g. navbar, comments, project notes, etc.)
@ilbailba You could make another issue suggesting that.
I'm not sure if it will work (since we'll need to add the attribute dynamically to the page - if we add it after the translation is done, it's useless) but it sounds more feasible than this.

**Comment by ilbailba** [comment]
> I don't think it makes sense to be in charge of the automatic translation ourselves.
> 
> However, considering this:
> > Google Translate translates the whole page and this is a much more difficult process.
> 
> There could be an addon that adds the `notranslate` attribute to parts of the page as the user chooses (e.g. navbar, comments, project notes, etc.)
> @ilbailba You could make another issue suggesting that.
> I'm not sure if it will work (since we'll need to add the attribute dynamically to the page - if we add it after the translation is done, it's useless) but it sounds more feasible than this.

I'll do this as soon as I'm available. but i didn't understand what you mean exactly. I think you're talking about a feature that allows translate to only translate the places the user wants. is that true? (I would appreciate if you speak a simpler english)

**Comment by WorldLanguages** [comment]
> I think you're talking about a feature that allows translate to only translate the places the user wants.

Something similar to that. An addon could possibly tell Google Translate to ignore certain parts of the website (we can only tell it what parts to ignore, not what parts to translate). The user could then choose what parts of the website aren't ignored.

**Comment by ilbailba** [comment]
> > I think you're talking about a feature that allows translate to only translate the places the user wants.
> 
> Something similar to that. An addon could possibly tell Google Translate to ignore certain parts of the website (we can only tell it what parts to ignore, not what parts to translate). The user could then choose what parts of the website aren't ignored.

hmm.. yes. logical. I guess I should open a new thread about this.
