### ISSUE TITLE
[Meta] Changes to projects.scratch.mit.edu

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4603]
https://github.com/LLK/scratch-www/pull/6773

We should check what addons could be affected by this.

**Comment by lisa-wolfgang** [comment]
As a summary, according to community speculation, this series of PRs implements authentication for unshared projects and requires a public token to be used to access shared projects, which is more difficult for external websites to obtain.

Addons that *will* or *could* be affected:
- `default-project` (customizable default project)
  - Unshared projects not created by the currently signed-in user will be inaccessible. This shouldn't cause the page to crash, but the addon won't work in this case. We may want to add a notice to the addon, or perhaps a new "project link" data/validation type :eyes:
  - All other projects will most likely continue working with the addon as expected, since the origin and therefore ability to access the tokens remain the same.
- `turbowarp-player` (TurboWarp button)
  - Will not work for unshared projects. There has been some discussion about a possible token-sharing mechanism between Scratch Addons and TurboWarp that would circumvent this. There is no need to make this addon work for unshared projects created by other users because users could never access their pages on Scratch anyway, which is where this feature resides.
  - Depending on how tokens for shared projects are implemented, TurboWarp may or may not be able to provide support for viewing shared projects.
- `live-featured-project` (live featured project)
  - Scratch embeds may or may not require changes to be compatible, so this is something we'll need to watch for info about.
  - The forkphorus and TurboWarp players will have the same issues noted for `turbowarp-player`.
- `feature-unshared` (feature unshared projects)
  - Scratch may not allow unshared projects to be featured anymore. However, if their backend doesn't automatically start rejecting the projects due to token issues, I guess it's possible that they'll overlook this.
- `hi-res-thumbnails` (high resolution thumbnails)
  - The addon changes `uploads.scratch.mit.edu` links to `cdn2.scratch.mit.edu` links. I didn't look into it much, but this could potentially cause thumbnail disappearance issues if changes are made to how either of these services function. Not high-prio right now, I don't think, but one to keep an eye on.
- `animated-thumb` (thumbnails setter)
  - Similar reason to `hi-res-thumbnails` in the reliance on `cdn2.scratch.mit.edu`. I didn't have time to look at it much in-depth, but from a quick skim, the uploading part of new thumbnails wouldn't be the issue, it would be retrieving the old thumbnail in case of an issue with the uploading of a thumbnail.

Addons that will **most likely not be affected**:
- `scratch-messaging` (Scratch Messaging)
  - I'm not very familiar with how the addon works, but since the addon has access to the user's token already, it shouldn't have any issues with formerly-shared projects that have associated messages.
  - If we utilize any public APIs (for example, to provide metadata or comment content) that are changed to require authentication, that could potentially cause issues. I don't know if the addon's environment counts as a different "origin."
- `remix-button` (remix button in own projects)
  - From a quick scan, it looks like the addon just calls Scratch's vanilla remix action, so there shouldn't be issues here.
- `last-edit-tooltip` (shared/edited dates tooltip)
  - Scratch includes this information with the rest of the downloaded project, and this addon only affects the project page, so no access issues will arise.
- `search-my-stuff` (search bar on My Stuff)
  - The addon itself doesn't make any project API calls -- it uses the site API.
- `block-count` (block count)
  - The block count is calculated locally.
- `project-info` (sprite and script count)
  - These counts are calculated locally.
- All other addons (probably)

I didn't make all of the addons, so it's entirely possible that I missed some problems or am being overparanoid -- let me know if I should change anything.

**Comment by apple502j** [comment]
I will submit a PR soon. Note that none of the addons mentioned above, except for default-project and TurboWarp stuff, will be affected. There is one addon that would definitely break, though.

**Comment by apple502j** [comment]
Affected addons:
- default-project stops working for some or all of the projects, potentially including shared ones. (depends on API edge case, if it requires token for shared ones it will be 100% broken)
- TurboWarp related addons can no longer open the user's own unshared projects.
- And another addon silently breaks without causing any harm whatsoever. You can guess which one it is.

**Comment by mxmou** [comment]
> And another addon silently breaks without causing any harm whatsoever. You can guess which one it is.

Progress bar?

**Comment by Chiroyce1** [comment]
These new token requirements will break addons on TurboWarp and other external sites - not Scratch itself, right?

**Comment by apple502j** [comment]
@Chiroyce1 Both, since you must pass the token even if you request from scratch.mit.edu origin (that's the whole point of the change)

**Comment by Chiroyce1** [comment]
> @Chiroyce1 Both, since you must pass the token even if you request from scratch.mit.edu origin (that's the whole point of the change)

Makes sense, so any requests made by the Scratch frontend will automatically have the token (which is what the PR does), but requests invoked by Scratch Addons cannot - so is there a way to figure out the token and then use it for requests made by SA?

**Comment by apple502j** [comment]
Yep, that's what I'm doing.
