### ISSUE TITLE
Confirm canceling comments

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4637]
Sometimes people accidentally hit the Cancel button after they write a comment, completely erasing it. A new option for the `confirm-actions` addon might help with this.

With a "confirm canceling comments" option, you would be asked if you really wanted to cancel your comment.

An alternative could be to just hide the button instead (carefully, though - it should still appear when replying).

**Comment by Chiroyce1** [comment]
Good idea, but we should be careful to not use the native `confirm()` function since that can be very confusing (as cancel is also an option there, at least in Firefox)
<img width="385" alt="image" src="https://user-images.githubusercontent.com/97374054/172011104-a7508c32-537f-4a70-b72e-06631da63b13.png">
