### ISSUE TITLE
Enhancing the Join() block.

### ISSUE THREAD

**Issue by TecFuture** [ScratchAddons/ScratchAddons#4763]
### Is your request related to a problem? Please describe.
Yes, whenever I am trying to join multiple seperate strings together, you would have to pull out more join blocks.

### Describe the solution you'd like
I would you like the addons to modify the join block, by increasing/decreasing the amount of arguments(like snap's join block).

In the join block there is a plus and subtract symbol to the right edge, by clicking plus there will be one more argument to join, by clicking subtract the rightmost argument would be removed.
### Describe alternatives you've considered
Manually attaching join blocks together

Adding an extra join block per argument.

**Comment by apple502j** [comment]
It doesn't seem like something we can do. If someone does PR it we'll review it, but for now this is "borderline impractical". Closing.

**Comment by BroJac5246** [comment]
I don't think this should be closed as "not planned," unless it's actually rejected. Since it's not, this should stay open. This would be a very useful feature, and it's certainly not impossible.

**Comment by WorldLanguages** [comment]
> I would you like the addons to modify the join block, by increasing/decreasing the amount of arguments

I think this was closed because we can't add more arguments to the "join" block. In theory, we could show a single "join" block with 3 arguments, and store it as 2 separate join blocks so it would still work for non-SA users, but that would be complex.
But of course, we could add an easier way to add another "join" block into existing join blocks. Maybe creating a new issue for that would be more appropriate.
