### ISSUE TITLE
Add more details to the contributing guidelines to help beginners

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5075]
### What the problem is
In the start, I wasn't quite sure how contributing was going to work, and I'm sure that's the experience some others have had when making their first PRs. Forgetting to make a new branch, not realizing that the workflows (GitHub Actions stuff) need to be enabled, oversights like that. To be more beginner friendly, I suggest we add more information to the [contributing guidelines](https://github.com/ScratchAddons/ScratchAddons/blob/master/CONTRIBUTING.md) to help any newcomers. Of course, there are tutorials out there, but it's easy for first-time contributors to just **_go_** and miss something.

### What we can do
Mainly, instead of one short sentence, use a concise list of steps to explain how you get to the PR part.
We can also link to the [SA FAQ page](https://scratchaddons.com/docs/develop/getting-started/creating-an-addon/) about creating a new addon so people know the syntaxes (for anyone who hasn't seen that FAQ page already).
We could also just link to help resources.

I think it would be a good idea to encourage beginners to contribute by making our guidelines appeal to them and help them avoid any mistakes. ❤️

**Comment by BroJac5246** [comment]
That's exactly what happened to me, it would be great if they were more detailed :)

**Comment by Norbiros** [comment]
Maybe we can add links to Github docs (about creating PR, pushing changes etc.)

**Comment by DNin01** [comment]
> Maybe we can add links to Github docs (about creating PR, pushing changes etc.)

Well, which articles would you like me to link to? You can also suggest them in the [PR](https://github.com/ScratchAddons/ScratchAddons/pull/5076).

Also, should we reference [the First Contributions guide](https://github.com/firstcontributions/first-contributions)? Anything else I should mention?

**Comment by RT-Borg** [comment]
Thank you @DNin01! Something like this would have been very helpful before my first PR.

It would also be helpful to document the expected interactions when you get feedback in a review. I've been unclear about when and whether I should mark review conversations as "resolved". Is that the author's role or the reviewer's role? If something was requested by a reviewer and the author has a question, should it be "resolved" because you've responded, or is it unresolved, because the request wasn't fulfilled?

It also hadn't been clear in my first PR how git worked with PRs. Somehow I had envisioned that once I had an active PR, if I made additional changes locally and pushed them, they would be in my personal remote github repository, but I'd still need to take another action to update the pull request. Of course I discovered that wasn't the way it works, but that was a short cause of confusion for me in my first contribution.
