### ISSUE TITLE
Motion block icon outline is not colored

### ISSUE THREAD

**Issue by Unkrown6YT** [ScratchAddons/ScratchAddons#5314]
### Description

I look closer that Motion Icon outline block is not colored

### Steps to reproduce

1. Enable Customizable block colors
2. Customize Motion Color Block

### Demonstration(s) and additional context

![Screenshot 2022-10-29 180622](https://user-images.githubusercontent.com/94491221/199536006-8629b122-0742-4465-970f-45022977f0de.png)

### Environment

Browser: Opera
Scratch Addons version: 1.29.0
Operating system: Windows 11

**Comment by lisa-wolfgang** [comment]
Can repro. Here's a screenshot with the block color being white, making the issue a little easier to see:

![image](https://user-images.githubusercontent.com/43426138/199541009-145d5a0f-162c-448f-982a-27d775cac7d4.png)

This happens because the color is included in the icon itself. It also occurs with the icon on loop blocks:

![image](https://user-images.githubusercontent.com/43426138/199542656-baa18513-28f9-4494-86cb-27f9320b7d3b.png)

**Comment by lisa-wolfgang** [comment]
Note that we should support changing the entirety of the icons as well due to https://github.com/ScratchAddons/ScratchAddons/discussions/5192. The upcoming color scheme will do away with the outline altogether.

**Comment by Unkrown6YT** [comment]
> Can repro. Here's a screenshot with the block color being white, making the issue a little easier to see:
> 
> ![image](https://user-images.githubusercontent.com/43426138/199541009-145d5a0f-162c-448f-982a-27d775cac7d4.png)
> 
> This happens because the color is included in the icon itself. It also occurs with the icon on loop blocks:
> 
> ![image](https://user-images.githubusercontent.com/43426138/199542656-baa18513-28f9-4494-86cb-27f9320b7d3b.png)

You can repro, have fun :D

**Comment by Samq64** [comment]
Reverted by #6216.

**Comment by WorldLanguages** [comment]
#6146 apparently had some bug fixes in preparation for the high-contrast colors mode but I'm not sure if they are actually related to this issue.
