### ISSUE TITLE
Combine or adjust the sections in the suggestion-type issue forms

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5436]
### Why this would be helpful/solve a problem

I've noticed that the Feature and New Addon issue forms I made don't always allow the most flexibility for writing issues:
- Sometimes filling in "What this change does" isn't always necessary because you're already describing most of it in the "Why this would be helpful/solve a problem" section and/or the suggestion is self-explanatory. Or maybe you haven't thought of the changes yet, or there may not be a specific change to mention, such as when the issue you're making is more like a discussion or problem report [(example)](https://github.com/ScratchAddons/ScratchAddons/issues/5306).
- The wording of "What this change does" is a bit inaccurate (and unclear to the writer) sometimes. I came up with "What this change does" when modifying the New Addon issue form to make one for suggesting features and improvements, but it didn't fit as well as I had hoped. It sounds like we're saying, "this is what the changes we're making are doing", not "**these are the changes we're suggesting**" (which sounds like what I meant to say).
- The majority of the time, _Possible alternatives_ and _Demonstration(s) and additional context_ are not filled out, so having them in the form, even if users don't fill them out, takes up space in issues, as they will be filled in as "_No response_". Some people may like to write possible alternative options in the "What this change does" section instead of the "Possible alternatives" section, and the "Demonstration(s) and additional context" section isn't really useful if you can describe parts of your suggestion in other parts of your issue, though it _is sometimes_ a good place to make clarifications, so...
- You can't easily modify or hide these sections if, for example, you don't need one of them. You can edit your comment after you create your issue, but there's no way to do it from the issue form interface.

### What this change does

There are a few ways to do this:

1. Merge **all** of the sections in the form into one "Description" section and have the following sub-sections (or something similar) be filled in as a placeholder for the user as shown below. They could be easily modified as necessary.
```
#### Why this would be helpful

#### My suggestion and how it works

#### Possible alternatives

#### Additional context

```
We could possibly choose a different name or keep the current name for the second section in the New Addon form - "What this _addon_ does" makes sense.

2. Keep the sections separate but change their names to make the form more flexible.

3. Merge some of the sections.

### Possible alternatives

We could also go back to Markdown issue templates, but it feels like a step backwards and it's less guided.

### Demonstration(s) and additional context

The Bug Report form doesn't need this change - we want users to include as much information as possible about bugs, and the way that form is built encourages users to do that.

**Comment by fractioneater** [comment]
> The majority of the time, Possible alternatives and Demonstration(s) and additional context are not filled out, so having them in the form, even if users don't fill them out, takes up space in issues, as they will be filled in as "No response".

When I don't use the "Demonstration(s) and additional context" section, I edit the comment and delete the whole section, instead of leaving "no response." I think this should happen automatically with inputs that aren't required.

**Comment by DNin01** [comment]
> > The majority of the time, Possible alternatives and Demonstration(s) and additional context are not filled out, so having them in the form, even if users don't fill them out, takes up space in issues, as they will be filled in as "No response".
> 
> When I don't use the "Demonstration(s) and additional context" section, I edit the comment and delete the whole section, instead of leaving "no response." I think this should happen automatically with inputs that aren't required.

GitHub would have to do that for us.

**Comment by RedGuy12** [comment]
For the New Addon form, we could rename the Possible Alternatives field to "Does another addon have similar functionality? Could this be merged with that?"


________________________________
From: DNin01 ***@***.***>
Sent: Friday, December 9, 2022 9:42:53 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Combine or adjust the sections in the suggestion-type issue forms (Issue #5436)


Why this would be helpful/solve a problem

I've noticed that the Feature and New Addon issue forms I made don't always allow the most flexibility for writing issues:

  *   Sometimes filling in "What this change does" isn't always necessary because you're already describing most of it in the "Why this would be helpful/solve a problem" section and/or the suggestion is self-explanatory. Or maybe you haven't thought of the changes yet, or there may not be a specific change to mention, such as when the issue you're making is more like a discussion or problem report (example)<https://github.com/ScratchAddons/ScratchAddons/issues/5306>.
  *   The wording of "What this change does" is a bit inaccurate (and unclear to the writer) sometimes. I came up with "What this change does" when modifying the New Addon issue form to make one for suggesting features and improvements, but it didn't fit as well as I had hoped. It sounds like we're saying, "this is what the changes we're making are doing", not "these are the changes we're suggesting" (which sounds like what I meant to say).
  *   The majority of the time, Possible alternatives and Demonstration(s) and additional context are not filled out, so having them in the form, even if users don't fill them out, takes up space in issues, as they will be filled in as "No response". Some people may like to write possible alternative options in the "What this change does" section instead of the "Possible alternatives" section, and the "Demonstration(s) and additional context" section isn't really useful if you can describe parts of your suggestion in other parts of your issue, though it is sometimes a good place to make clarifications, so...
  *   You can't easily modify or hide these sections if, for example, you don't need one of them. You can edit your comment after you create your issue, but there's no way to do it from the issue form interface.

What this change does

There are a few ways to do this:

  1.  Merge all of the sections in the form into one "Description" section and have the following sub-sections (or something similar) be filled in as a placeholder for the user as shown below. They could be easily modified as necessary.

#### Why this would be helpful

#### My suggestion and how it works

#### Possible alternatives

#### Additional context



We could possibly choose a different name or keep the current name for the second section in the New Addon form - "What this addon does" makes sense.

  1.  Keep the sections separate but change their names to make the form more flexible.

  2.  Merge some of the sections.

Possible alternatives

We could also go back to Markdown issue templates, but it feels like a step backwards and it's less guided.

Demonstration(s) and additional context

The Bug Report form doesn't need this change - we want users to include as much information as possible about bugs, and the way that form is built encourages users to do that.
