### ISSUE TITLE
Can't copy scripts/costumes to other sprite at bottom of sprites pane

### ISSUE THREAD

**Issue by damightyq** [ScratchAddons/ScratchAddons#5528]
### Description

When I try to copy a script or costume to a sprite at the bottom of the pane, it goes back up to the row before that. That's annoying. Please fix it.

### Steps to reproduce

1. drag a script or costume at a sprite at the bottom of the pane

goes back up a row

### Environment

Browser: Any
Scratch Addons version: latest ver.
Operating system: Any

**Comment by DNin01** [comment]
This might be a Scratch bug if I'm understanding. Try enabling the "Disable sprite wobble in sprite pane" addon.

**Comment by BroJac5246** [comment]
Is this a Scratch Addons bug or a Scratch bug? It sounds like the latter.

Also, the "Environment" section is about where _you_ encountered this bug. Sometimes bugs that occur in one environment don't occur in another. An example of that is a bug in a Chromium browser not occurring in Firefox, or vice versa.

**Comment by WorldLanguages** [comment]
@damightyq Please make sure this bug isn't also happening without Scratch Addons enabled.

**Comment by DNin01** [comment]
Based on your description, I'm pretty sure this is the bug you're talking about:

https://user-images.githubusercontent.com/106490990/215287798-efa13fd1-2688-443c-a991-3ed2359e4c74.mp4

This is a Scratch bug and is not caused by Scratch Addons. We've already made a "Disable sprite wobble in sprite pane" addon that fixes this problem, so try enabling that.

**Comment by Samq64** [comment]
The disable sprite wobble addon is supported to help with that.

**Comment by damightyq** [comment]
Ok, Sorry I haven't said anything. I forgot about this existing. Thanks though!
