### ISSUE TITLE
Variable Precision

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#5685]
### Why this would be helpful

Some scratch projects need extra floating-point precision.

### How this addon works

Adds a slider to control how many digits of precision are included (how precise the arithmetic blocks are). For the variables, possibly position, and lists.

### Possible alternatives

Could be merged with this [issue](https://github.com/ScratchAddons/ScratchAddons/issues/922).

**Comment by DNin01** [comment]
This would affect how Scratch projects run, leading to projects that can only be run with the help of Scratch Addons, wouldn't it?

**Comment by WorldLanguages** [comment]
> Adds a slider to control how many digits of precision are included. 

What do you mean by _included_? How many are shown in the monitor? Or how precise the arithmetic blocks are?

**Comment by 22yeetz22** [comment]
> > Adds a slider to control how many digits of precision are included.
> 
> What do you mean by _included_? How many are shown in the monitor? Or how precise the arithmetic blocks are?

How precise the arithmetic blocks are

**Comment by DNin01** [comment]
> > > Adds a slider to control how many digits of precision are included.
> > 
> > 
> > What do you mean by _included_? How many are shown in the monitor? Or how precise the arithmetic blocks are?
> 
> How precise the arithmetic blocks are

I'm sorry, but unfortunately we can't really do that because the behavior of existing projects would change and some projects may require this functionality, and [we aren't allowed to mention browser extensions on Scratch](https://scratch.mit.edu/discuss/topic/284272/). We also don't really want to be sharing projects that can't be run with unmodified Scratch to Scratch.

This could become a feature in [TurboWarp](https://turbowarp.org), though, since it's technically a separate "ecosystem" with its own community.

**Comment by CST1229** [comment]
(Also, the current number precision is all we can really do without either limiting it to only integers or sacrificing performance by a lot.)
