### ISSUE TITLE
Auto-hiding volume slider incompatible with reverse order of project controls

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6055]

**Comment by DNin01** [comment]
Oops! Didn't consider that. I suppose this might also be a problem in the RTL layout.

I think we should release a patch as soon as possible.

**Comment by Secret-chest** [comment]
Thanks.

**Comment by WorldLanguages** [comment]
What does "incompatible" mean here?

**Comment by CST1229** [comment]
> What does "incompatible" mean here?

I don't think it's supposed to look like this.

![](https://github.com/ScratchAddons/ScratchAddons/assets/68464103/2751aa8b-92bd-4ad0-84aa-ca36c4a1694c)

**Comment by DNin01** [comment]
Similar issue in RTL layout:
![The volume icon and part of the slider intersects the green flag and stop sign](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/b7aa9feb-32ee-407e-8b3d-5fc65f476d84)

Looks okay when both RTL and Reverse order of project controls are enabled.

**Comment by DNin01** [comment]
The reason this happens is because of this property:
https://github.com/ScratchAddons/ScratchAddons/blob/6687d1baad9328b8f9d9138d6536648c58ab9d38/addons/vol-slider/hover.css#L8
This is supposed to prevent the mouse position and clone counter displays from shifting when the volume slider expands, but it causes the slider to overlap with the project controls when the layout is flipped.

If we move the mouse position and clone counter displays to the left of the volume slider when using Reverse order of project controls, we might be able to find an easier solution.

**Comment by WorldLanguages** [comment]
cc @mxmou I think you might know the best solution
