### ISSUE TITLE
Prevent Google Analytics from loading on scratch.mit.edu

### ISSUE THREAD

**Issue by RedLight-Scratch** [ScratchAddons/ScratchAddons#6134]
### Why this would be helpful

This would be helpful for blocking Scratch (via Google Analytics) from tracking you.

### How this addon works

Self Explanatory

### Possible alternatives

None

**Comment by DNin01** [comment]
We may not be able to do this long-term because Google's new extensions platform, Manifest V3, which we will soon have to move to, does not support web request blocking in the same way Manifest V2 does. Also, if a user wanted to block GA on Scratch, they'd likely also want to block it on other websites as well, which this addon won't cover. The user is better off using another solution at that point.

I believe Google has already made a Chrome extension that allows the user to opt out of Google Analytics, and many browsers such as Firefox, Edge and Safari have tracking-prevention features, so those are already options for users who really don't want GA tracking them.

**Comment by Hans5958** [comment]
As said before despite MV3 concerns, this is out of scope and there are adblockers that did this better (I recommend [uBlock Origin](https://ublockorigin.com/))
