### ISSUE TITLE
confirm-actions confirmations don't show description and have broken close buttons

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6153]
### Description

When using the confirmations addon in 1.33.0-prerelease, the confirmation boxes don't have a description and the close button doesn't do anything.

### Steps to reproduce

1. Enable 1.33.0-prerelease
2. Go to a profile page
3. Enable confirm-actions
4. Trigger a confirmation

### Demonstration(s) and additional context

![A broken unfollow dialog](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/db0f2b59-dba9-4ae0-8eee-742b4c3d2538)
On scratch-www pages, the white part doesn't show up either.

### Environment

Browser: Edge 114
Scratch Addons version: 1.33.0-prerelease, I don't know how to get a hash
Operating system: Windows 11

**Comment by Samq64** [comment]
Could this possibly be related to that vanilla bug on `scratchr2` pages?
![image](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/47fe3a98-83a7-4b3c-9efb-a99870175028)

**Comment by mxmou** [comment]
This is caused by the scratchClass change (#6105): apparently `addon.tab.confirm()` calls `addon.tab.scratchClass()` unconditionally but only uses the result if it's called on the project page with `{useEditorClasses: true}`. There might be similar cases elsewhere in the code, so I think the simplest solution is making `addon.tab.scratchClass()` never throw when not on the project page.

`addon.tab.confirm()` and `addon.tab.prompt()` should probably `await addon.tab.scratchClassReady()` (they're already async).

**Comment by WorldLanguages** [comment]
> I think the simplest solution is making `addon.tab.scratchClass()` never throw when not on the project page.

Not sure if that makes sense, though. `addon.tab.scratchClass` only makes sense in project pages.

**Comment by mybearworld** [comment]
> > I think the simplest solution is making `addon.tab.scratchClass()` never throw when not on the project page.
> 
> Not sure if that makes sense, though. `addon.tab.scratchClass` only makes sense in project pages.

It could just return `null`, or `"notProject"` or something like that. Clearly having it throw brings issues

**Comment by WorldLanguages** [comment]
> Clearly having it throw brings issues

Well, we're having issues because the contract changed. The real question is, should we allow it to silently fail when not in a project page?
I guess we could restore the old behavior instead of throwing, but warn to the console if `addon.tab.scratchClass()` is being used outside a project page. Thanks for the bug report!
