### ISSUE TITLE
Logitech F310 Gamepad not recognized on Scratch Addons

### ISSUE THREAD

**Issue by wow-hello** [ScratchAddons/ScratchAddons#6248]
### Description

Hi there! I just bought a Logitech F310 gamepad because I wanted to try it out with Scratch Addons. I enabled the "Gamepad support" addon and opened it in the Scratch project editor, but it says "No controllers detected. Try plugging one in and pressing a button on it." I had plugged in the controller and pressed a button, but it still didn't recognize it. Trying my controller with other games like Portal seemed to work fine. Has anyone else had this issue?

Thanks in advance,
Damian

### Steps to reproduce

1. plug in a Logitech F310 to one of the USB ports on your computer
2. enable the Gamepad support addon
3. open the Scratch project editor
4. click the controller icon at the top right, above the player

### Environment

Browser: **Brave 1.52.122 (Chromium 114.0.5735.110)**
Scratch Addons version: **v1.33.1**
Operating system: **Ubuntu 23.04**

**Comment by GarboMuffin** [comment]
The gamepad support addon relies on your browser and operating system to have the proper drivers, so the fix would be there.

Since you're using Ubuntu, it's quite likely you installed your browser through the Snap Store. You have to go to the Snap Store, find your browser, open up its permission settings there, and make sure that the joystick/gamepad permission is enabled (usually it isn't by default)

**Comment by wow-hello** [comment]
Thanks for the clarification! I added the permissions and now it works.
