### ISSUE TITLE
move addons setting to main menu out of color setttings

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/ScratchAddons#6338]
### Description

Shouldn't the new ScratchAddons settings button be in the main settings drop down menu, not buried in the more specific color settings submenu, as it is not specifically/exclusively color settings related?

### Steps to reproduce

1.
2.
3.

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by WorldLanguages** [comment]
@ksdavidc Do you mean this?

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/9feb1c3a-9cfe-47b8-94eb-41771cd23242)


This button only appears if "customizable block colors" is enabled. And it links directly to that addon's settings, so that users can quickly disable it or change its colors if wanted.
We still expect users to get to Scratch Addons settings through their browser UI.

In the future, we will consider adding our own "Scratch Addons settings" button to the settings menu, outside the color settings submenu, as you're saying.

**Comment by ksdavidc** [comment]
Oh, I get it...just saw the flash. At any rate, it is a quick way to get to the settings, which is nice. 

afterthought...might it make sense to combine the "managed by" and "Addon Settings" buttons? Now it's grayed, but I would expect it not to be grayed (since it is active), but clickable...I suppose it's a matter of style --- "de gustibus non est disputandum"

**Comment by WorldLanguages** [comment]
It's grayed because we do not support toggling the "customizable block colors" from outside the settings page, and it wouldn't make sense to allow the user to switch to original/high-contrast while the addon is enabled.
Maybe in the future we can try to extend this submenu in a better way, but this is what we came with this time.

**Comment by ksdavidc** [comment]
Fair enough. Thank you for responding....
