### ISSUE TITLE
Scratch is migrating some pages to scratch.org

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6508]
https://scratch.mit.edu/discuss/topic/765450/

**Comment by GarboMuffin** [comment]
It is pure speculation, to be clear

**Comment by DNin01** [comment]
If they were moving domains, they'd have to change the code on their repositories, right? So we should have a little bit of a forewarning?

I don't think it will happen this weekend, though.

**Comment by WorldLanguages** [comment]
Yeah, it' should be quite unlikely they'll change domains without publicly announcing it.

**Comment by Samq64** [comment]
There doesn't really seem to be any mentions of Scratch.org on their GH org yet. https://github.com/search?q=org%3Ascratchfoundation+scratch.org&type=code

**Comment by Samq64** [comment]
Since this was just speculation it didn't happen and won't anytime soon.

**Comment by DNin01** [comment]
scratch.org was announced last week:
https://scratch.mit.edu/discuss/topic/765450/

It said that some static pages were moving to scratch.org, and that everything else like project, studio, search, profile, and forum pages (which are all how you interact with the Scratch community) will stay on the scratch.mit.edu site, at least for for now.

**Comment by Samq64** [comment]
Even if most of the pages aren't ones Scratchers would encounter often we could still consider adding a host permission and adding support for a couple addons like dark mode.

**Comment by DNin01** [comment]
In the case that we add more host permissions, we might want to consider setting up a page or notification inside Scratch Addons asking for such host permissions. The permissions could be optional, otherwise the extension would be disabled and we wouldn't have a chance to explain why we want permission, which could lead to uninstalls and confused users.

It would also be an opportunity to take another look at how we handle host permissions and look into possible improvements:
- Should we ask for permission to scratchaddons.com? It would allow us to directly communicate with our website at any time and maybe even use it as a backup storage area if something happens to the extension. (Related: #6448)
- IIRC, all host permissions on MV3 Firefox Add-ons are optional, so we have to open a page requesting those permissions. Is there any way to improve the user experience of that, such as changing the wording or creating an onboarding experience with granting permissions as one of the steps?
- Should we allow the user to use Scratch Addons without granting every host permission? Some of them aren't strictly necessary. When these permissions are revoked by the user, we ask for those permissions back, which makes sense, but we also block access to Scratch Addons until they are granted.

**Comment by WorldLanguages** [comment]
Here is my and mxmou's stance: [(source](https://github.com/ScratchAddons/ScratchAddons/issues/7562#issuecomment-2182073987))

> Few addons run on scratch.org pages - dark mode is the most important one - and users don't visit them often. Supporting them would be nice but it isn't very important.

**Comment by DNin01** [comment]
scratch.org looks like it has a completely different purpose (resources for parents and educators), at least for now, and its layout is completely different, so customizations to scratch.mit.edu wouldn't make much sense on scratch.org. We could, however, apply basic style changes such as _a_ dark mode theme if the user has set a dark color scheme in `dark-www`.

Of course, that could change when the redirects are established.

**Comment by Secret-chest** [comment]
scratch.org is a WordPress marketing site. Qe don't need to worry about it.

**Comment by rickbot-dot** [comment]
> scratch.org is a WordPress marketing site. Qe don't need to worry about it.

I remember always going to Scratch using that link when it used to redirect to the main page. Guess I can't do that anymore.

**Comment by Samq64** [comment]
Scratch.org now redirects to https://scratchfoundation.org.
