### ISSUE TITLE
Links styled by `colorblind` on scratch-www pages are still bold when they're not set to bold

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6532]
### Description

Even though I have selected the underline option in `colorblind`, links are still showing up bold as usual. This also includes scratchr2 pages when using the `scratchr2` addon.

### Steps to reproduce

1. Enable the underline option of `colorblind`
2. Go to a scratch-www page with links

### Demonstration(s) and additional context

![Links still being bold.](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/54f4ab87-6fe0-4177-8a13-b17a0df95d5d)

### Environment

Browser: Edge 115
Scratch Addons version: 1.34.0
Operating system: Windows

**Comment by WorldLanguages** [comment]
I'm not sure this is unintentional. @DNin01 might be able to answer

**Comment by mybearworld** [comment]
> I'm not sure this is unintentional. @/DNin01 might be able to answer

It's quite unintuitive behavior, regardless, and should at least be reconsidered.

**Comment by Samq64** [comment]
Related: #6503

**Comment by DNin01** [comment]
This works as intended. Links on `scratch-www` are already bold. The setting is only here because there are some links, mostly on `scratchr2` and on the footer that aren't bold.

I agree it is unintuitive, though. The "Default" setting shouldn't really be here now because it practically disables the addon. It's simply a remnant from when it was going to be a more general colorblind accessibility addon.

**Comment by DNin01** [comment]
Let's use #6503 to track this.
