### ISSUE TITLE
Missing translation for "flag"

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#6579]
### Description

When I open the debugger and a project is running, instead of reading the correct translation of "flag" for the "when flag clicked" events, I read the word "flag" even in the Italian translation.

### Steps to reproduce

1. Enable the "debugger" addon
2. Open a project
3. Click the green flag
4. Click the debugger button above the Stage
5. Click the "Threads" tab
6. the (Italian) translation of "when flag clicked" is wrong, as it is "quando si clicca _flag_" instead of being "quando si clicca _bandiera verde_" (note: that could be shortened in "quando si clicca _bandiera_" if necessary).

### Environment

Browser: Firefox 116.0.3 (64 bit)
Scratch Addons version: 1.34.0
Operating system: MacOS Big Sur

**Comment by mxmou** [comment]
`find-bar` has the same issue:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/a2b83718-e59e-4b40-bace-4d5a5ae8c6c0)

I think this happens because the Transifex action puts the string `global/blocks/green-flag` and other strings whose keys start with `global/` into a file named `global.json` instead of `_general.json`. The relevant code is [here](https://github.com/ScratchAddons/l10n-script/blob/main/scripts/pull.js#L45).
English: [`_general.json`](https://github.com/ScratchAddons/ScratchAddons/blob/master/addons-l10n/en/_general.json)
Italian: [`_general.json`](https://github.com/ScratchAddons/ScratchAddons/blob/master/addons-l10n/it/_general.json), [`global.json`](https://github.com/ScratchAddons/ScratchAddons/blob/master/addons-l10n/it/global.json)

**Comment by WorldLanguages** [comment]
> I think this happens because the Transifex action puts the string `global/blocks/green-flag` and other strings whose keys start with `global/` into a file named `global.json` instead of `_general.json`.

Huh, good catch.

**Comment by mxmou** [comment]
I think changing the `global` prefix to `_general` would also work.

**Comment by WorldLanguages** [comment]
> I think changing the `global` prefix to `_general` would also work.

Yeah, looks like that would also work:
https://github.com/ScratchAddons/l10n-script/blob/0f6a199f8311d8bf3bea3b3abfec0a555c7c7454/scripts/pull.js#L45
