### ISSUE TITLE
Decimal settings

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6604]
### Why this would be helpful

Some future addons might want to have non-integer number settings.

### My suggestion

Adding decimal settings to the addon manifest.

### Possible alternatives

#6021

### Additional context

This would work better than #6021 for #6555.

**Comment by WorldLanguages** [comment]
Personally, I wouldn't consider this until a second addon comes out that would benefit from this.

`editor-number-arrow-keys` only needs this because the setting is **literally a number**, not measured in pixels, nor megapixels, nor anything. I don't think it's worth it to require all settings page implementations (including TurboWarp's!) to support decimals just because of that addon. And because of it, we know adding numbers with decimals [can go wrong](https://0.30000000000000004.com/) very easily.

**Comment by Samq64** [comment]
I guess #6021 would be better then.

**Comment by WorldLanguages** [comment]
I would say the same thing about #6021, I think. There's 3 separate issues about supporting decimals, so I'm confused on whether this one is a duplicate or not, but it could stay open.

**Comment by Samq64** [comment]
> I'm confused on whether this one is a duplicate or not

I would consider it one because I noticed a float setting was listed as an alternative in #6021 after creating this one.
