### ISSUE TITLE
ScratchTools `live-character-counts` not working with Scratch Addons `project-notes-tabs`

### ISSUE THREAD

**Issue by rgantzos** [ScratchAddons/ScratchAddons#6606]
### Description

(Thanks to Jazza for reporting)

![Image](https://user-images.githubusercontent.com/86856959/263875203-3ae65c55-f649-4dee-9a63-2f3b76bae733.png)

When using ScratchTools and Scratch Addons, the font size is incorrect within the Scratch Addons project notes tabs.

### Steps to reproduce

1. Enable Project Notes Tabs from SA
2. Enable Live Character Counts from STE
3. Go to the project page of a project you own

### Demonstration(s) and additional context

ScratchTools issue: [#677](https://github.com/STForScratch/ScratchTools/issues/677)

### Environment

Browser: 116.0.5845.110
Scratch Addons version: v1.34.0-pre
Operating system: MacOS Sonoma

**Comment by DNin01** [comment]
Browser extension conflicts aren't really worth resolving IMO - it's not exclusively either extension's fault.

**Comment by WorldLanguages** [comment]
@DNin01 This was also a pending task on #6258 I think, so I don't know why we wouldn't resolve this.

**Comment by DNin01** [comment]
> @DNin01 This was also a pending task on #6258 I think, so I don't know why we wouldn't resolve this.

It's just that that is a conflict between two addons in Scratch Addons, not this, which is a conflict between two browser extensions.

Unless we've made accommodations for ScratchTools specifically in the past, we can't always expect to be compatible with other extensions. It's like how Android apps can't always utilize the full potential of the phone's camera because it's different in almost every phone.

Things like this will always happen. It's just the nature of add-ons. We can't fix every possible extension conflict.

I would understand if we accommodate for popular extensions, though, like we did for Redux DevTools, if I understand? Maybe ScratchTools would be a good one to support.

**Comment by WorldLanguages** [comment]
I'm not sure why you're seeing this so broadly. This is a specific change that is very easy to do and that will also help avoid conflicts with the upcoming addon from SA. Or are we talking about whether these types of issues should be created in the first place? I think it's okay as long as there aren't too many.

**Comment by rgantzos** [comment]
> Browser extension conflicts aren't really worth resolving IMO - it's not exclusively either extension's fault.

It doesn't need to be either extension's fault for a fix to be necessary.

**Comment by BroJac5246** [comment]
> > @ DNin01 This was also a pending task on #6258 I think, so I don't know why we wouldn't resolve this.
> 
> It's just that that is a conflict between two addons in Scratch Addons, not this, which is a conflict between two browser extensions.

In most cases (including this one), a conflict like this with another browser extension for Scratch will be the result of an oversight of at least one of the extensions. And since it's an oversight, it's likely to cause issues in the future (like, within that extension), so it should be fixed even if it's not currently causing any errors when just that extension is in use.

Obviously, whichever extension made the oversight should be the one in which it's fixed.

> Unless we've made accommodations for ScratchTools specifically in the past, we can't always expect to be compatible with other extensions. It's like how Android apps can't always utilize the full potential of the phone's camera because it's different in almost every phone.

I'm not sure this is the best comparison. It's a little less straightforward in the Android ecosystem. iOS users might assume that it's the operating system's responsibility to provide the perfect image, but that's not the case. Like in most OSs, the camera is simply a piece of hardware that any app, including the manufacturer's heavily optimized camera app, can access and process as that app sees fit. And if an app doesn't want to provide that processing, then they can request the OEM's camera app to do the heavy lifting. That's not very relevant here.

> Things like this will always happen. It's just the nature of add-ons. We can't fix every possible extension conflict.

Sure, but this is nevertheless an issue in our end.

> I would understand if we accommodate for popular extensions, though, like we did for Redux DevTools, if I understand? Maybe ScratchTools would be a good one to support.

How do we define popular? I'm not saying we shouldn't support other extensions (on the contrary, I think we should), but I think a better policy might be to fix all issues on our end that arise.
