### ISSUE TITLE
`better-quoter`: do not break assets.scratch.mit.edu image URL quoting

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6754]
### Why this would be helpful

Often, I want to quote an image posted by another user. If they hosted that with assets, I will have to add `/get_image/.%2E` myself.

### My suggestion

Automatically add `/get_image/.%2E` to the image when it's quoted with `better-quoter`.

**Comment by WorldLanguages** [comment]
I never considered this! Fortunately, forumers often remove images when quoting.

**Comment by DNin01** [comment]
Are you saying that there's a bug where `/get_image/.%2E` is unintentionally omitted from quoted selections or some people don't append that to the end and then the image doesn't display, so this is an enhancement that will add it for you?

In the latter case, it doesn't _hurt_, but I think it should be in a more sensible place (if we put it in this addon, that means it has to be enabled and you have to quote a selection in order to use this, all while not knowing it), and I don't know if we really have anywhere to put it. It also doesn't fix the original post for you.

**Comment by mxmou** [comment]
> Are you saying that there's a bug where `/get_image/.%2E` is unintentionally omitted from quoted selections or some people don't append that to the end and then the image doesn't display, so this is an enhancement that will add it for you?

It's a bug - the addon reads the image's `src`, which doesn't include the `get_image` part.

**Comment by WorldLanguages** [comment]
What does the vanilla Scratch "quote" button do?
