### ISSUE TITLE
Remix tree button dissapears when the window gets too small, and does not get added back

### ISSUE THREAD

**Issue by Jazza-231** [ScratchAddons/ScratchAddons#6956]
### Description

What should happen: The remix button should appear once the window has enough room, like the vanilla buttons.
What does happen: It doesn't. This also affects the download projecrt button (not merged)project

### Steps to reproduce

1. Open a project with the remix tree addon enabled
2. Resize the window, either by opening dev tools on the right, or actually making your browser window smaller
3. Notice that some buttons have gone, now make the window bigger, notice how vanilla buttons are all back, but SA added buttons dont reappear.

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/81956724/d9938858-3bb3-4c34-92cd-9d189db8af92

### Environment

Browser: Brave.
Scratch Addons version: Current
Operating system: Windows 11

**Comment by DNin01** [comment]
I wonder if Scratch regenerates this row of buttons every time the layout changes, removing the buttons we added. In that case, we would just have to re-add our buttons as needed.

**Comment by DNin01** [comment]
Scratch also hides some of the buttons when there'd not enough space. We should consider whether we should automatically hide some of our buttons or try to cram them in.

**Comment by DNin01** [comment]
This happens when the window is resized from 768px wide or more to less than 768px or the other way around.

Looks like this is handled at [`src/views/preview/presentation.jsx#L381`](https://github.com/scratchfoundation/scratch-www/blob/7853388e59142221cec2ee404e71b36aca168808/src/views/preview/presentation.jsx#L381) in the source code for the Scratch website.

This issue isn't limited to addons that add buttons. `last-edit-tooltip` is also affected because it works with the share date label, another element that is modified when the screen size dips above or below 768px.

@mxmou, do you happen to know any potential fixes for this?

**Comment by mxmou** [comment]
Removing `reduxEvents` from the `waitForElement` call is enough to fix this in last-edit-tooltip. In remix-tree-button, the `urlChange` listener will need to be replaced with a `waitForElement` loop.

**Comment by WorldLanguages** [comment]
> Removing `reduxEvents` from the `waitForElement` call is enough to fix this in last-edit-tooltip.

Hmm, removing all the redux events optimizations wouldn't be optimal.
We could 1) add a "resize" event that can be added into the `reduxEvents` list or through other parts of the API, or 2) attempt to modify the behavior of waitForElement so that it always queries all selectors again if the window was resized.
