### ISSUE TITLE
Addons don't run in iframes

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#702]
**Is your feature request related to a problem? Please describe.**

The contact form and the preview in the forums are iframes. Addons don't affect them.

**Describe the solution you'd like**

Userscripts and userstyles should be able to run in iframes.

**Comment by apple502j** [comment]
Contact Us form is at different origin, so it's impossible.

Forum preview can be handled as part of the parent page.

**Comment by mxmou** [comment]
The contact form doesn't have a `src`.

**Comment by mxmou** [comment]
> Forum preview can be handled as part of the parent page.

Not in a userstyle.

**Comment by mxmou** [comment]
This causes the preview on the forums to look different from the actual post when a dark theme or 2.0 3.0 is enabled.

**Comment by WorldLanguages** [comment]
@mxmou Sorry I don't know what you're talking about, can you post a screenshot?

**Comment by mxmou** [comment]
> @mxmou Sorry I don't know what you're talking about, can you post a screenshot?

Post:
![image](https://user-images.githubusercontent.com/51849865/99884942-d3997000-2c31-11eb-9f0a-7a677ef4de98.png)

Preview:
![image](https://user-images.githubusercontent.com/51849865/99884946-ddbb6e80-2c31-11eb-9b30-d5555b6f3bd6.png)

**Comment by WorldLanguages** [comment]
@mxmou What do you mean by "preview"?

**Comment by mxmou** [comment]
> @mxmou What do you mean by "preview"?

The checkmark button on the right side of the toolbar shows a preview of the post.

**Comment by WorldLanguages** [comment]
Ohhhh. The preview of the post. I see

**Comment by WorldLanguages** [comment]
@mxmou I could get iframes to work with addons, but I had issues with the 2 places where you would find them useful. These two are `about:blank` iframes.
1. The whole DOM is remade each time the user requests another forum preview, so all CSS is gone, and stuff breaks because the `<template id="scratch-addons>` is supposed to be there all the time.
2. Scratch Addons gets injected in the "contact us" iframe, but the window "load" event never fires for some reason I'm not sure about. I don't think it makes sense to code a specific way to detect loading in that specific iframe.

I think I won't be supporting about:blank iframes. Since these iframes are "first party" (and we don't have access to third party iframes anyway), I'd suggest you use JavaScript to style these (and restyle them when necessary, for example, when a user requests another preview).

**Comment by WorldLanguages** [comment]
The PR does make addon work on iframes, but does not solve the specific request from this issue's description, so I created another one with a more specific title.
