### ISSUE TITLE
Console log will be flooded on Firefox

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#703]
**Describe the bug**
Console log gets flooded by 297 SA logs describing "messages from background", at least on Firefox.

**To Reproduce**
Open new tab (for example, front page) then open console.

**Expected behavior**
No (or a few) debug messages

**Device (please complete the following information):**
win10, firefox82.0.3

**Additional context**
Log:
[flooded log.txt](https://github.com/ScratchAddons/ScratchAddons/files/5516947/flooded.log.txt)

**Comment by Hans5958** [comment]
You sure? Same setup, only a few logs.

![image](https://user-images.githubusercontent.com/11584103/98670381-3a42a200-2385-11eb-88ba-9ebf6f2e4fe1.png)

**Comment by areeq0325** [comment]
Is this still an issue?
If so, you might want to add the `firefox` label.

**Comment by TheColaber** [comment]
@apple502j Please confirm this is still a problem... Hans was not able to repo, and on chrome I get only one:
![image](https://user-images.githubusercontent.com/72760579/110568899-c4c3c400-8121-11eb-9926-c39b0f6291f4.png)

**Comment by RedGuy12** [comment]
I get a ton... why do we even need "messages from the background"?
________________________________

**Comment by WorldLanguages** [comment]
I'd like to move this into a new issue so that we can restructure how content scripts get data from the background page. This "flood" is because of some themes like dark mode, that need to be injected very fast in order to avoid flashes. There are alternative ways that don't require spamming messages, but they may take more time. We should test alternatives
