### ISSUE TITLE
Unsupported browser page: add Export Settings button

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7125]
### Why this would be helpful

Related to #6669
Part of MV3 roadmap: #6876

> This will allow users running old browser versions to export their settings before (and after) the extension goes away.

Nowadays, each user's settings is like a piece of art, that is hard to memorize, and basically impossible to replicate exactly if lost. It would be very rude if the Unsupported Browser page not only kicked you out from using the extension, but also made it impossible for users to export their selection of settings.

### My suggestion

The "unsupported browser" page will live in `chrome-extension://`, but the page will be a full-screen iframe of the current page (scratchaddons.com/unsupported-browser).

Clicking the new "Export Settings" / "View settings as file" buttons will run `parent.postMessage()`, giving control back to the extension.

If the user has no internet connection, they won't be able to export their settings. It's also a good opportunity to display a simple "unsupported browser" text in that case.

### Possible alternatives

There might be other ways to let users export settings if their browser is unsupported, but we need to quickly add one before we upgrade to Manifest V3.

**Comment by DNin01** [comment]
I'd honestly try to recreate the unsupported browser page from the website inside Scratch Addons for offline support, instead of loading an embedded scratchaddons.com webpage. If the first time the user sees this page, they don't have an obvious option to export their settings, they may never find it.

**Comment by DNin01** [comment]
Also, we should only ever automatically open this page once or when the user tries to interact with Scratch Addons so it doesn't disturb them if they keep Scratch Addons installed and turned on.

**Comment by DNin01** [comment]
Page idea:

> # Unsupported Browser
>
> Scratch Addons doesn't support the browser you are currently using. Please update your browser to use Scratch Addons.
>
> Scratch Addons supports:
> - Chrome \<version>+ (same for other Chromium browsers)
> - Firefox \<version>+
>
> ## Options
>
> Don't worry, you can export your settings so you still have them for the next time you use Scratch Addons. You can also remove the extension from your browser below.
> 
> <kbd>Export settings</kbd>\
> <kbd>View raw settings</kbd>\
> <kbd>Remove Scratch Addons</kbd>

**Comment by WorldLanguages** [comment]
> Also, we should only ever automatically open this page once or when the user tries to interact with Scratch Addons so it doesn't disturb them if they keep Scratch Addons installed and turned on.

Right now, I think we also open the unsupported browser page 1) on install 2) each time the browser is restarted.

**Comment by DNin01** [comment]
> I think it's nice that we can continue to update the unsupported browser page, even if the browser will not continue to ship extension updates. Do we really want to give up to that?
> I guess your suggestion is to recreate the current version of the page for offline support, but is it really worth it?
> I would just include 2 or 3 paragraphs as the offline unsupported-browser page. Not much of CSS needed. Few people will see that page at all.

That's a good point. It's just if the user can't export their settings from the offline "unsupported browser" page, then they'll be looking for it, can't find/access it, then give up on trying to export their settings, even if their internet connection is restored later.

Heck, maybe we should even just not display this page unless they have an internet connection, which would probably be a more relevant time to open that page because you have to be online to use the Scratch website. More precisely, if they were offline on browser restart, we probably wouldn't display it until they navigate to Scratch while connected to the internet. Only thing to think about then is what happens when the user tries to open the extension's popup or settings page...

> 2\) each time the browser is restarted.

We should only do that if the user can easily figure out how to remove the extension, or if we let them remove the extension from the page. We don't really want to leave them with no idea how to get this to go away every time they start up their browser.

I guess an exception to that would be if the internet connection was offline, then the next time the extension is restarted with an internet connection, we load the online "unsupported browser" page.

**Comment by WorldLanguages** [comment]
I think I'll change it, so that it doesn't show the unsupported-browser page on each browser startup. Showing the page only if the extension has just updated would be better.
Counter-intuitively, this change could mean the page is shown more often to some users though 🤔 Depends on whether the user restarts their browser often and whether they keep getting updates or not.
