### ISSUE TITLE
`fullscreen`: Toolbar doesn't show when hovering outside page on Firefox

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7191]
### Description

On Chromium-based browsers without the browser fullscreen setting but with the hover setting the toolbar is shown when the mouse cursor is above the page, but on Firefox the toolbar is only shown when aiming for the tiny vertical strip inside the page.

### Steps to reproduce

1. Use Firefox
2. Enable `fullscreen`
3. Disable the browser fullscreen setting
4. Enable the hide toolbar and show on hover settings
5. Open a project in fullscreen

### Environment

Browser: Firefox 122
Scratch Addons version: 1.36.0
Operating system: Linux

**Comment by DNin01** [comment]
I don't have Firefox, but if you could insert `console.log(e.clientY);` above line 61, inside the `mouseleave` event listener and tell me what shows up in the console (including if no logs appear), that would help.

My current theory is that `clientY` might be evaluating to `undefined`, which is I guess considered less than any number, so that could be what's happening. If it is, changing the condition to `(e.clientY < 8 || !e.clientY)` should fix the problem.

**Comment by Samq64** [comment]
The event is never triggered. Attaching it to the body instead fixes it though.
