### ISSUE TITLE
Scratch adding refuses to load in Orion both mobile and desktop

### ISSUE THREAD

**Issue by Greenpickles987** [ScratchAddons/ScratchAddons#7359]
I installed scratch addons both the Firefox and chrome extensions and yet it refuses to load.

**Comment by Samq64** [comment]
Which versions and where did you install it from?

**Comment by BroJac5246** [comment]
> Which version of the extension and where did you install it from?

Probably the current version from CWS and Firefox Add-ons, based on what they said.

**Comment by WorldLanguages** [comment]
What's Orion?

**Comment by CST1229** [comment]
> What's Orion?

Probably a browser.

**Comment by DNin01** [comment]
> > What's Orion?
> 
> Probably a browser.

I found @OrionBrowser on GitHub.

**Comment by BroJac5246** [comment]
[Orion](https://kagi.com/orion/) is a WebKit-based browser that has experimental support for both Chrome and Firefox extensions. Their [docs indicate](https://help.kagi.com/orion/browser-extensions/macos-extensions.html) that they only support approximately 70% of WebExtensions APIs and they intend to add support for more later. We shouldn't bother supporting it because this is a beta feature that very few people use.

**Comment by BlueGoat11** [comment]
Yea, I’ve never heard of Orion. I guess wait until they add support themselves?

**Comment by Samq64** [comment]
Safari support will be more beneficial and there's already a draft PR open but it won't get merged for a while.

**Comment by DNin01** [comment]
I would guess we are not going to be explicitly supporting the Orion browser anytime soon, and it's on its way to supporting many Chrome and Firefox extensions anyway.
