### ISSUE TITLE
i dont know its cratches fault or this

### ISSUE THREAD

**Issue by GREGDGamer1** [ScratchAddons/ScratchAddons#7445]
### Description

i dont know its cratches fault or this anger time
WHEN I SAVE IT WILL INFINITLY LOAD AND NEVER SAVE
WHEN I CLICK ON BLOCKS IT DOESNT WORK SO I HAVE TO MANULY  PUT IT WHEN GREEN FLAG IS CLICK

### Steps to reproduce

1.
2.
3.

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by DNin01** [comment]
Unfortunately, we can't really help solve your problem without more information. It would at least be nice to know the versions of your browser, operating system, and Scratch Addons, and, if you can, what you were doing before the issue, or if you can consistently reproduce it, the steps to make it happen.

Here are some things you could try:
- Review which addons you have enabled and check that they aren't unexpectedly changing the behavior of Scratch. (There is an addon that makes it so that you have to _hold the Ctrl key_ and click blocks to execute them)
- Turn off the Scratch Addons extension from your browser's Extensions menu and try again.
- Try again in a different Scratch project.

**Comment by BroJac5246** [comment]
> Try again in a different Scratch project.

Definitely try this one. Projects won't save if the assets are too large, which could be the problem.

**Comment by WorldLanguages** [comment]
?
