### ISSUE TITLE
ESLint workflow not working

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7658]
Error message on every run since... oh, I don't know when:
```
Run npx eslint . --config .eslintrc.json --ext .js
  npx eslint . --config .eslintrc.json --ext .js
  shell: /usr/bin/bash -e {0}
Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
Error: Process completed with exit code 2.
```
The check still succeeds, it just can't evaluate anything. (That's probably why we haven't noticed.)

It might also be a good time to revise the rules, see if we should be more restrictive about certain things like unused variables.

@WorldLanguages @Hans5958

**Comment by Hans5958** [comment]
Seems like a breaking change on ESLint v9 where a new config file format is introduced. Note that the current workflow will always use the latest version.

https://eslint.org/docs/latest/use/configure/migration-guide#start-using-flat-config-files

The quick patch would be locking ESLint to v8.x.

PS. I'm blaming Apple for replacing Codacy as the code quality check to this workflow that we have to maintain because she hates these kind of tools.

**Comment by DNin01** [comment]
Reminder about #7134

**Comment by WorldLanguages** [comment]
> Reminder about #7134

Yes, I keep forgetting about that one. I guess my brain will only notice after actions stop working...

**Comment by Hans5958** [comment]
> Reminder about #7134

Oh, yeah. I also have to add the version there, specifically on the `npx eslint ...` line to `npx eslint@8 ...`>. I would do it later, or I welcome if anyone want to edit it sooner by themselves.

**Comment by Hans5958** [comment]
I have made the necessary changes on #7134 by updated the ESLint config to be able to be used on ESLint v9.x.
