### ISSUE TITLE
Disable annoying deletion confirmation

### ISSUE THREAD

**Issue by LIZARD-OFFICIAL-77** [ScratchAddons/ScratchAddons#7966]
### Why this would be helpful

The default sprite deletion confirmation dialog cannot be disabled.

### My suggestion

Disable the confirmation if scratchaddons is installed, since there is an option to do that anyways.

**Comment by Samq64** [comment]
> Disable the confirmation if scratchaddons is installed, since there is an option to do that anyways.

We removed ours when Scratch added theirs so this would be a new addon.

**Comment by DNin01** [comment]
My thought on this is that it would be too easy to delete the wrong thing, and since you can only undo the last deletion, you might lose something forever. It's annoying but it's an important safeguard.

An alternative would be to **add an addon to multi-select sprites and then delete them all at once**, still with _one_ confirmation after making your selection.

But a way to remove the confirmation message entirely might be too extreme. Over anything we have to offer, we don't want to cause people to lose work. You'll thank us later.

But that's just my opinion.

**Comment by Samq64** [comment]
> But a way to remove the confirmation message entirely might be too extreme.

Having the dangerous tag on it should be fine. We already have disable auto save.

**Comment by LIZARD-OFFICIAL-77** [comment]
What are y'all smoking?! There is an addon for confirmations ANYWAYS. What is the point of not removing the one scratch team foolishly added?!

**Comment by Samq64** [comment]
The addon was for adding a confirmation, not removing it. If the addon was updated to remove Scratch's confirmation it would do the opposite of what users turned it on for.

**Comment by CubesterYT** [comment]
I propose that we add a bunch of toggles on the addon, so that users can CHOOSE which confirmations they want.

**Comment by DNin01** [comment]
> I propose that we add a bunch of toggles on the addon, so that users can CHOOSE which confirmations they want.

A potential problem with that is we already have an addon that lets you add confirmations for certain actions, so then we'd have two addons that are for confirmation customization, one for adding new ones and one for changing existing ones.

**Comment by CubesterYT** [comment]
I'm talking about the current existing confirmations addon, we add options to that. And what we could do is add an option about the close confirmation to it, but it's toggled on by default, since it'll be scratch's default one. Disabling the option removes it. Its odd but it seems right.

**Comment by LIZARD-OFFICIAL-77** [comment]
JUST REMOVE THE DAMN CONFIRMATION. THERE IS AN ADDON IF YOU CANNOT LIVE WITHOUT IT.

**Comment by CST1229** [comment]
> JUST REMOVE THE DAMN CONFIRMATION. THERE IS AN ADDON IF YOU CANNOT LIVE WITHOUT IT.

the thing is, removing the confirmation by default would change vanilla scratch behavior without users knowing, which is especially bad since it's a safety feature to prevent data loss (this is why the disable autosave addon is marked as dangerous and is obviously not enabled by default!)
so, at most, there would be a new addon to disable the sprite delete confirmation (the existing confirmations addon is only for the website/account-related actions, and we don't tend to mix website and editor features into a single addon)

**Comment by Samq64** [comment]
> which is especially bad since it's a safety feature to prevent data loss 

Edit > restore sprite still exists, so data loss isn't a problem unless deleting multiple sprites in a row.

**Comment by CubesterYT** [comment]
> > JUST REMOVE THE DAMN CONFIRMATION. THERE IS AN ADDON IF YOU CANNOT LIVE WITHOUT IT.
> 
> the thing is, removing the confirmation by default when installing scratch addons would change vanilla scratch behavior without users knowing, which is especially bad since it's a safety feature to prevent data loss (this is why the disable autosave addon is marked as dangerous and is obviously not enabled by default!)
> so, at most, there would be a new addon to disable the sprite delete confirmation (the existing confirmations addon is only for the website/account-related actions, and we don't tend to mix website and editor features into a single addon)

Yeah, which is why above, in my recent comment, I said that adding the vanilla confirmation to the addon but default enabled works as a work around, so turning the toggle off would allow disabling.

**Comment by WorldLanguages** [comment]
@LIZARD-OFFICIAL-77 I recommend you unsubscribe from this thread if you want to stop receiving emails about it.
